// ============================================================
// SVコード生成: 出力基盤（インデント管理・ファイルヘッダー・ポートリスト）
// ============================================================
#include "internal/codegen/sv/codegen.hpp"

#include <string>
#include <vector>

namespace cm::codegen::sv {

// === コード出力ヘルパー ===

void SVCodeGen::emit(const std::string& code) {
    append(code);
}

void SVCodeGen::emitLine(const std::string& code) {
    append_line(indent() + code);
}

void SVCodeGen::emitIndented(const std::string& code) {
    append(indent() + code);
}

void SVCodeGen::increaseIndent() {
    indent_level_++;
}

void SVCodeGen::decreaseIndent() {
    if (indent_level_ > 0)
        indent_level_--;
}

std::string SVCodeGen::indent() const {
    return std::string(indent_level_ * options_.indentSpaces, ' ');
}

// === ファイルヘッダー ===

void SVCodeGen::emitFileHeader() {
    emitLine("// SystemVerilog generated by Cm compiler");
    emitLine("// ターゲット: SystemVerilog IEEE 1800-2017");
    emitLine("`timescale 1ns / 1ps");
    append_line("");
}

// === モジュール生成 ===

void SVCodeGen::emitPortList(const std::vector<SVPort>& ports) {
    if (ports.empty()) {
        emitLine("();");
        return;
    }

    emitLine("(");
    increaseIndent();
    for (size_t i = 0; i < ports.size(); i++) {
        const auto& port = ports[i];
        std::string dir;
        switch (port.direction) {
            case SVPort::Input:
                dir = "input ";
                break;
            case SVPort::Output:
                dir = "output ";
                break;
            case SVPort::InOut:
                dir = "inout ";
                break;
        }
        std::string line = dir + port.sv_type + " " + port.name + port.array_suffix;
        if (!port.init_value.empty()) {
            line += " = " + port.init_value;
        }
        if (i < ports.size() - 1) {
            line += ",";
        }
        emitLine(line);
    }
    decreaseIndent();
    emitLine(");");
}

}  // namespace cm::codegen::sv
