# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/shadowlink/Documents/git/Cm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/shadowlink/Documents/git/Cm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shadowlink/Documents/git/Cm/CMakeFiles /Users/shadowlink/Documents/git/Cm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shadowlink/Documents/git/Cm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named cm

# Build rule for target.
cm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cm
.PHONY : cm

# fast build rule for target.
cm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/build
.PHONY : cm/fast

#=============================================================================
# Target rules for targets named cm_runtime

# Build rule for target.
cm_runtime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cm_runtime
.PHONY : cm_runtime

# fast build rule for target.
cm_runtime/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm_runtime.dir/build.make CMakeFiles/cm_runtime.dir/build
.PHONY : cm_runtime/fast

src/codegen/common/runtime_functions.o: src/codegen/common/runtime_functions.cpp.o
.PHONY : src/codegen/common/runtime_functions.o

# target to build an object file
src/codegen/common/runtime_functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/common/runtime_functions.cpp.o
.PHONY : src/codegen/common/runtime_functions.cpp.o

src/codegen/common/runtime_functions.i: src/codegen/common/runtime_functions.cpp.i
.PHONY : src/codegen/common/runtime_functions.i

# target to preprocess a source file
src/codegen/common/runtime_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/common/runtime_functions.cpp.i
.PHONY : src/codegen/common/runtime_functions.cpp.i

src/codegen/common/runtime_functions.s: src/codegen/common/runtime_functions.cpp.s
.PHONY : src/codegen/common/runtime_functions.s

# target to generate assembly for a file
src/codegen/common/runtime_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/common/runtime_functions.cpp.s
.PHONY : src/codegen/common/runtime_functions.cpp.s

src/codegen/common/type_converter.o: src/codegen/common/type_converter.cpp.o
.PHONY : src/codegen/common/type_converter.o

# target to build an object file
src/codegen/common/type_converter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/common/type_converter.cpp.o
.PHONY : src/codegen/common/type_converter.cpp.o

src/codegen/common/type_converter.i: src/codegen/common/type_converter.cpp.i
.PHONY : src/codegen/common/type_converter.i

# target to preprocess a source file
src/codegen/common/type_converter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/common/type_converter.cpp.i
.PHONY : src/codegen/common/type_converter.cpp.i

src/codegen/common/type_converter.s: src/codegen/common/type_converter.cpp.s
.PHONY : src/codegen/common/type_converter.s

# target to generate assembly for a file
src/codegen/common/type_converter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/common/type_converter.cpp.s
.PHONY : src/codegen/common/type_converter.cpp.s

src/codegen/js/codegen.o: src/codegen/js/codegen.cpp.o
.PHONY : src/codegen/js/codegen.o

# target to build an object file
src/codegen/js/codegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/js/codegen.cpp.o
.PHONY : src/codegen/js/codegen.cpp.o

src/codegen/js/codegen.i: src/codegen/js/codegen.cpp.i
.PHONY : src/codegen/js/codegen.i

# target to preprocess a source file
src/codegen/js/codegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/js/codegen.cpp.i
.PHONY : src/codegen/js/codegen.cpp.i

src/codegen/js/codegen.s: src/codegen/js/codegen.cpp.s
.PHONY : src/codegen/js/codegen.s

# target to generate assembly for a file
src/codegen/js/codegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/js/codegen.cpp.s
.PHONY : src/codegen/js/codegen.cpp.s

src/codegen/js/control_flow.o: src/codegen/js/control_flow.cpp.o
.PHONY : src/codegen/js/control_flow.o

# target to build an object file
src/codegen/js/control_flow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/js/control_flow.cpp.o
.PHONY : src/codegen/js/control_flow.cpp.o

src/codegen/js/control_flow.i: src/codegen/js/control_flow.cpp.i
.PHONY : src/codegen/js/control_flow.i

# target to preprocess a source file
src/codegen/js/control_flow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/js/control_flow.cpp.i
.PHONY : src/codegen/js/control_flow.cpp.i

src/codegen/js/control_flow.s: src/codegen/js/control_flow.cpp.s
.PHONY : src/codegen/js/control_flow.s

# target to generate assembly for a file
src/codegen/js/control_flow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/js/control_flow.cpp.s
.PHONY : src/codegen/js/control_flow.cpp.s

src/codegen/js/emit_expressions.o: src/codegen/js/emit_expressions.cpp.o
.PHONY : src/codegen/js/emit_expressions.o

# target to build an object file
src/codegen/js/emit_expressions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/js/emit_expressions.cpp.o
.PHONY : src/codegen/js/emit_expressions.cpp.o

src/codegen/js/emit_expressions.i: src/codegen/js/emit_expressions.cpp.i
.PHONY : src/codegen/js/emit_expressions.i

# target to preprocess a source file
src/codegen/js/emit_expressions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/js/emit_expressions.cpp.i
.PHONY : src/codegen/js/emit_expressions.cpp.i

src/codegen/js/emit_expressions.s: src/codegen/js/emit_expressions.cpp.s
.PHONY : src/codegen/js/emit_expressions.s

# target to generate assembly for a file
src/codegen/js/emit_expressions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/js/emit_expressions.cpp.s
.PHONY : src/codegen/js/emit_expressions.cpp.s

src/codegen/js/emit_statements.o: src/codegen/js/emit_statements.cpp.o
.PHONY : src/codegen/js/emit_statements.o

# target to build an object file
src/codegen/js/emit_statements.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/js/emit_statements.cpp.o
.PHONY : src/codegen/js/emit_statements.cpp.o

src/codegen/js/emit_statements.i: src/codegen/js/emit_statements.cpp.i
.PHONY : src/codegen/js/emit_statements.i

# target to preprocess a source file
src/codegen/js/emit_statements.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/js/emit_statements.cpp.i
.PHONY : src/codegen/js/emit_statements.cpp.i

src/codegen/js/emit_statements.s: src/codegen/js/emit_statements.cpp.s
.PHONY : src/codegen/js/emit_statements.s

# target to generate assembly for a file
src/codegen/js/emit_statements.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/js/emit_statements.cpp.s
.PHONY : src/codegen/js/emit_statements.cpp.s

src/codegen/llvm/core/context.o: src/codegen/llvm/core/context.cpp.o
.PHONY : src/codegen/llvm/core/context.o

# target to build an object file
src/codegen/llvm/core/context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/context.cpp.o
.PHONY : src/codegen/llvm/core/context.cpp.o

src/codegen/llvm/core/context.i: src/codegen/llvm/core/context.cpp.i
.PHONY : src/codegen/llvm/core/context.i

# target to preprocess a source file
src/codegen/llvm/core/context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/context.cpp.i
.PHONY : src/codegen/llvm/core/context.cpp.i

src/codegen/llvm/core/context.s: src/codegen/llvm/core/context.cpp.s
.PHONY : src/codegen/llvm/core/context.s

# target to generate assembly for a file
src/codegen/llvm/core/context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/context.cpp.s
.PHONY : src/codegen/llvm/core/context.cpp.s

src/codegen/llvm/core/interface.o: src/codegen/llvm/core/interface.cpp.o
.PHONY : src/codegen/llvm/core/interface.o

# target to build an object file
src/codegen/llvm/core/interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/interface.cpp.o
.PHONY : src/codegen/llvm/core/interface.cpp.o

src/codegen/llvm/core/interface.i: src/codegen/llvm/core/interface.cpp.i
.PHONY : src/codegen/llvm/core/interface.i

# target to preprocess a source file
src/codegen/llvm/core/interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/interface.cpp.i
.PHONY : src/codegen/llvm/core/interface.cpp.i

src/codegen/llvm/core/interface.s: src/codegen/llvm/core/interface.cpp.s
.PHONY : src/codegen/llvm/core/interface.s

# target to generate assembly for a file
src/codegen/llvm/core/interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/interface.cpp.s
.PHONY : src/codegen/llvm/core/interface.cpp.s

src/codegen/llvm/core/intrinsics.o: src/codegen/llvm/core/intrinsics.cpp.o
.PHONY : src/codegen/llvm/core/intrinsics.o

# target to build an object file
src/codegen/llvm/core/intrinsics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/intrinsics.cpp.o
.PHONY : src/codegen/llvm/core/intrinsics.cpp.o

src/codegen/llvm/core/intrinsics.i: src/codegen/llvm/core/intrinsics.cpp.i
.PHONY : src/codegen/llvm/core/intrinsics.i

# target to preprocess a source file
src/codegen/llvm/core/intrinsics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/intrinsics.cpp.i
.PHONY : src/codegen/llvm/core/intrinsics.cpp.i

src/codegen/llvm/core/intrinsics.s: src/codegen/llvm/core/intrinsics.cpp.s
.PHONY : src/codegen/llvm/core/intrinsics.s

# target to generate assembly for a file
src/codegen/llvm/core/intrinsics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/intrinsics.cpp.s
.PHONY : src/codegen/llvm/core/intrinsics.cpp.s

src/codegen/llvm/core/mir_to_llvm.o: src/codegen/llvm/core/mir_to_llvm.cpp.o
.PHONY : src/codegen/llvm/core/mir_to_llvm.o

# target to build an object file
src/codegen/llvm/core/mir_to_llvm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/mir_to_llvm.cpp.o
.PHONY : src/codegen/llvm/core/mir_to_llvm.cpp.o

src/codegen/llvm/core/mir_to_llvm.i: src/codegen/llvm/core/mir_to_llvm.cpp.i
.PHONY : src/codegen/llvm/core/mir_to_llvm.i

# target to preprocess a source file
src/codegen/llvm/core/mir_to_llvm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/mir_to_llvm.cpp.i
.PHONY : src/codegen/llvm/core/mir_to_llvm.cpp.i

src/codegen/llvm/core/mir_to_llvm.s: src/codegen/llvm/core/mir_to_llvm.cpp.s
.PHONY : src/codegen/llvm/core/mir_to_llvm.s

# target to generate assembly for a file
src/codegen/llvm/core/mir_to_llvm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/mir_to_llvm.cpp.s
.PHONY : src/codegen/llvm/core/mir_to_llvm.cpp.s

src/codegen/llvm/core/operators.o: src/codegen/llvm/core/operators.cpp.o
.PHONY : src/codegen/llvm/core/operators.o

# target to build an object file
src/codegen/llvm/core/operators.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/operators.cpp.o
.PHONY : src/codegen/llvm/core/operators.cpp.o

src/codegen/llvm/core/operators.i: src/codegen/llvm/core/operators.cpp.i
.PHONY : src/codegen/llvm/core/operators.i

# target to preprocess a source file
src/codegen/llvm/core/operators.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/operators.cpp.i
.PHONY : src/codegen/llvm/core/operators.cpp.i

src/codegen/llvm/core/operators.s: src/codegen/llvm/core/operators.cpp.s
.PHONY : src/codegen/llvm/core/operators.s

# target to generate assembly for a file
src/codegen/llvm/core/operators.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/operators.cpp.s
.PHONY : src/codegen/llvm/core/operators.cpp.s

src/codegen/llvm/core/print_codegen.o: src/codegen/llvm/core/print_codegen.cpp.o
.PHONY : src/codegen/llvm/core/print_codegen.o

# target to build an object file
src/codegen/llvm/core/print_codegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/print_codegen.cpp.o
.PHONY : src/codegen/llvm/core/print_codegen.cpp.o

src/codegen/llvm/core/print_codegen.i: src/codegen/llvm/core/print_codegen.cpp.i
.PHONY : src/codegen/llvm/core/print_codegen.i

# target to preprocess a source file
src/codegen/llvm/core/print_codegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/print_codegen.cpp.i
.PHONY : src/codegen/llvm/core/print_codegen.cpp.i

src/codegen/llvm/core/print_codegen.s: src/codegen/llvm/core/print_codegen.cpp.s
.PHONY : src/codegen/llvm/core/print_codegen.s

# target to generate assembly for a file
src/codegen/llvm/core/print_codegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/print_codegen.cpp.s
.PHONY : src/codegen/llvm/core/print_codegen.cpp.s

src/codegen/llvm/core/terminator.o: src/codegen/llvm/core/terminator.cpp.o
.PHONY : src/codegen/llvm/core/terminator.o

# target to build an object file
src/codegen/llvm/core/terminator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/terminator.cpp.o
.PHONY : src/codegen/llvm/core/terminator.cpp.o

src/codegen/llvm/core/terminator.i: src/codegen/llvm/core/terminator.cpp.i
.PHONY : src/codegen/llvm/core/terminator.i

# target to preprocess a source file
src/codegen/llvm/core/terminator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/terminator.cpp.i
.PHONY : src/codegen/llvm/core/terminator.cpp.i

src/codegen/llvm/core/terminator.s: src/codegen/llvm/core/terminator.cpp.s
.PHONY : src/codegen/llvm/core/terminator.s

# target to generate assembly for a file
src/codegen/llvm/core/terminator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/terminator.cpp.s
.PHONY : src/codegen/llvm/core/terminator.cpp.s

src/codegen/llvm/core/types.o: src/codegen/llvm/core/types.cpp.o
.PHONY : src/codegen/llvm/core/types.o

# target to build an object file
src/codegen/llvm/core/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/types.cpp.o
.PHONY : src/codegen/llvm/core/types.cpp.o

src/codegen/llvm/core/types.i: src/codegen/llvm/core/types.cpp.i
.PHONY : src/codegen/llvm/core/types.i

# target to preprocess a source file
src/codegen/llvm/core/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/types.cpp.i
.PHONY : src/codegen/llvm/core/types.cpp.i

src/codegen/llvm/core/types.s: src/codegen/llvm/core/types.cpp.s
.PHONY : src/codegen/llvm/core/types.s

# target to generate assembly for a file
src/codegen/llvm/core/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/types.cpp.s
.PHONY : src/codegen/llvm/core/types.cpp.s

src/codegen/llvm/core/utils.o: src/codegen/llvm/core/utils.cpp.o
.PHONY : src/codegen/llvm/core/utils.o

# target to build an object file
src/codegen/llvm/core/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/utils.cpp.o
.PHONY : src/codegen/llvm/core/utils.cpp.o

src/codegen/llvm/core/utils.i: src/codegen/llvm/core/utils.cpp.i
.PHONY : src/codegen/llvm/core/utils.i

# target to preprocess a source file
src/codegen/llvm/core/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/utils.cpp.i
.PHONY : src/codegen/llvm/core/utils.cpp.i

src/codegen/llvm/core/utils.s: src/codegen/llvm/core/utils.cpp.s
.PHONY : src/codegen/llvm/core/utils.s

# target to generate assembly for a file
src/codegen/llvm/core/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/core/utils.cpp.s
.PHONY : src/codegen/llvm/core/utils.cpp.s

src/codegen/llvm/native/codegen.o: src/codegen/llvm/native/codegen.cpp.o
.PHONY : src/codegen/llvm/native/codegen.o

# target to build an object file
src/codegen/llvm/native/codegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/native/codegen.cpp.o
.PHONY : src/codegen/llvm/native/codegen.cpp.o

src/codegen/llvm/native/codegen.i: src/codegen/llvm/native/codegen.cpp.i
.PHONY : src/codegen/llvm/native/codegen.i

# target to preprocess a source file
src/codegen/llvm/native/codegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/native/codegen.cpp.i
.PHONY : src/codegen/llvm/native/codegen.cpp.i

src/codegen/llvm/native/codegen.s: src/codegen/llvm/native/codegen.cpp.s
.PHONY : src/codegen/llvm/native/codegen.s

# target to generate assembly for a file
src/codegen/llvm/native/codegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/native/codegen.cpp.s
.PHONY : src/codegen/llvm/native/codegen.cpp.s

src/codegen/llvm/native/target.o: src/codegen/llvm/native/target.cpp.o
.PHONY : src/codegen/llvm/native/target.o

# target to build an object file
src/codegen/llvm/native/target.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/native/target.cpp.o
.PHONY : src/codegen/llvm/native/target.cpp.o

src/codegen/llvm/native/target.i: src/codegen/llvm/native/target.cpp.i
.PHONY : src/codegen/llvm/native/target.i

# target to preprocess a source file
src/codegen/llvm/native/target.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/native/target.cpp.i
.PHONY : src/codegen/llvm/native/target.cpp.i

src/codegen/llvm/native/target.s: src/codegen/llvm/native/target.cpp.s
.PHONY : src/codegen/llvm/native/target.s

# target to generate assembly for a file
src/codegen/llvm/native/target.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/native/target.cpp.s
.PHONY : src/codegen/llvm/native/target.cpp.s

src/codegen/llvm/optimizations/inst_combine/inst_combiner.o: src/codegen/llvm/optimizations/inst_combine/inst_combiner.cpp.o
.PHONY : src/codegen/llvm/optimizations/inst_combine/inst_combiner.o

# target to build an object file
src/codegen/llvm/optimizations/inst_combine/inst_combiner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/inst_combine/inst_combiner.cpp.o
.PHONY : src/codegen/llvm/optimizations/inst_combine/inst_combiner.cpp.o

src/codegen/llvm/optimizations/inst_combine/inst_combiner.i: src/codegen/llvm/optimizations/inst_combine/inst_combiner.cpp.i
.PHONY : src/codegen/llvm/optimizations/inst_combine/inst_combiner.i

# target to preprocess a source file
src/codegen/llvm/optimizations/inst_combine/inst_combiner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/inst_combine/inst_combiner.cpp.i
.PHONY : src/codegen/llvm/optimizations/inst_combine/inst_combiner.cpp.i

src/codegen/llvm/optimizations/inst_combine/inst_combiner.s: src/codegen/llvm/optimizations/inst_combine/inst_combiner.cpp.s
.PHONY : src/codegen/llvm/optimizations/inst_combine/inst_combiner.s

# target to generate assembly for a file
src/codegen/llvm/optimizations/inst_combine/inst_combiner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/inst_combine/inst_combiner.cpp.s
.PHONY : src/codegen/llvm/optimizations/inst_combine/inst_combiner.cpp.s

src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.o: src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.cpp.o
.PHONY : src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.o

# target to build an object file
src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.cpp.o
.PHONY : src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.cpp.o

src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.i: src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.cpp.i
.PHONY : src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.i

# target to preprocess a source file
src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.cpp.i
.PHONY : src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.cpp.i

src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.s: src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.cpp.s
.PHONY : src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.s

# target to generate assembly for a file
src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.cpp.s
.PHONY : src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.cpp.s

src/codegen/llvm/optimizations/optimization_manager.o: src/codegen/llvm/optimizations/optimization_manager.cpp.o
.PHONY : src/codegen/llvm/optimizations/optimization_manager.o

# target to build an object file
src/codegen/llvm/optimizations/optimization_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/optimization_manager.cpp.o
.PHONY : src/codegen/llvm/optimizations/optimization_manager.cpp.o

src/codegen/llvm/optimizations/optimization_manager.i: src/codegen/llvm/optimizations/optimization_manager.cpp.i
.PHONY : src/codegen/llvm/optimizations/optimization_manager.i

# target to preprocess a source file
src/codegen/llvm/optimizations/optimization_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/optimization_manager.cpp.i
.PHONY : src/codegen/llvm/optimizations/optimization_manager.cpp.i

src/codegen/llvm/optimizations/optimization_manager.s: src/codegen/llvm/optimizations/optimization_manager.cpp.s
.PHONY : src/codegen/llvm/optimizations/optimization_manager.s

# target to generate assembly for a file
src/codegen/llvm/optimizations/optimization_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/optimization_manager.cpp.s
.PHONY : src/codegen/llvm/optimizations/optimization_manager.cpp.s

src/codegen/llvm/optimizations/peephole/peephole_optimizer.o: src/codegen/llvm/optimizations/peephole/peephole_optimizer.cpp.o
.PHONY : src/codegen/llvm/optimizations/peephole/peephole_optimizer.o

# target to build an object file
src/codegen/llvm/optimizations/peephole/peephole_optimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/peephole/peephole_optimizer.cpp.o
.PHONY : src/codegen/llvm/optimizations/peephole/peephole_optimizer.cpp.o

src/codegen/llvm/optimizations/peephole/peephole_optimizer.i: src/codegen/llvm/optimizations/peephole/peephole_optimizer.cpp.i
.PHONY : src/codegen/llvm/optimizations/peephole/peephole_optimizer.i

# target to preprocess a source file
src/codegen/llvm/optimizations/peephole/peephole_optimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/peephole/peephole_optimizer.cpp.i
.PHONY : src/codegen/llvm/optimizations/peephole/peephole_optimizer.cpp.i

src/codegen/llvm/optimizations/peephole/peephole_optimizer.s: src/codegen/llvm/optimizations/peephole/peephole_optimizer.cpp.s
.PHONY : src/codegen/llvm/optimizations/peephole/peephole_optimizer.s

# target to generate assembly for a file
src/codegen/llvm/optimizations/peephole/peephole_optimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/peephole/peephole_optimizer.cpp.s
.PHONY : src/codegen/llvm/optimizations/peephole/peephole_optimizer.cpp.s

src/codegen/llvm/optimizations/vectorization/vectorizer.o: src/codegen/llvm/optimizations/vectorization/vectorizer.cpp.o
.PHONY : src/codegen/llvm/optimizations/vectorization/vectorizer.o

# target to build an object file
src/codegen/llvm/optimizations/vectorization/vectorizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/vectorization/vectorizer.cpp.o
.PHONY : src/codegen/llvm/optimizations/vectorization/vectorizer.cpp.o

src/codegen/llvm/optimizations/vectorization/vectorizer.i: src/codegen/llvm/optimizations/vectorization/vectorizer.cpp.i
.PHONY : src/codegen/llvm/optimizations/vectorization/vectorizer.i

# target to preprocess a source file
src/codegen/llvm/optimizations/vectorization/vectorizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/vectorization/vectorizer.cpp.i
.PHONY : src/codegen/llvm/optimizations/vectorization/vectorizer.cpp.i

src/codegen/llvm/optimizations/vectorization/vectorizer.s: src/codegen/llvm/optimizations/vectorization/vectorizer.cpp.s
.PHONY : src/codegen/llvm/optimizations/vectorization/vectorizer.s

# target to generate assembly for a file
src/codegen/llvm/optimizations/vectorization/vectorizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/codegen/llvm/optimizations/vectorization/vectorizer.cpp.s
.PHONY : src/codegen/llvm/optimizations/vectorization/vectorizer.cpp.s

src/frontend/lexer/token.o: src/frontend/lexer/token.cpp.o
.PHONY : src/frontend/lexer/token.o

# target to build an object file
src/frontend/lexer/token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/lexer/token.cpp.o
.PHONY : src/frontend/lexer/token.cpp.o

src/frontend/lexer/token.i: src/frontend/lexer/token.cpp.i
.PHONY : src/frontend/lexer/token.i

# target to preprocess a source file
src/frontend/lexer/token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/lexer/token.cpp.i
.PHONY : src/frontend/lexer/token.cpp.i

src/frontend/lexer/token.s: src/frontend/lexer/token.cpp.s
.PHONY : src/frontend/lexer/token.s

# target to generate assembly for a file
src/frontend/lexer/token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/lexer/token.cpp.s
.PHONY : src/frontend/lexer/token.cpp.s

src/frontend/parser/parser_expr.o: src/frontend/parser/parser_expr.cpp.o
.PHONY : src/frontend/parser/parser_expr.o

# target to build an object file
src/frontend/parser/parser_expr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/parser/parser_expr.cpp.o
.PHONY : src/frontend/parser/parser_expr.cpp.o

src/frontend/parser/parser_expr.i: src/frontend/parser/parser_expr.cpp.i
.PHONY : src/frontend/parser/parser_expr.i

# target to preprocess a source file
src/frontend/parser/parser_expr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/parser/parser_expr.cpp.i
.PHONY : src/frontend/parser/parser_expr.cpp.i

src/frontend/parser/parser_expr.s: src/frontend/parser/parser_expr.cpp.s
.PHONY : src/frontend/parser/parser_expr.s

# target to generate assembly for a file
src/frontend/parser/parser_expr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/parser/parser_expr.cpp.s
.PHONY : src/frontend/parser/parser_expr.cpp.s

src/frontend/parser/parser_module.o: src/frontend/parser/parser_module.cpp.o
.PHONY : src/frontend/parser/parser_module.o

# target to build an object file
src/frontend/parser/parser_module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/parser/parser_module.cpp.o
.PHONY : src/frontend/parser/parser_module.cpp.o

src/frontend/parser/parser_module.i: src/frontend/parser/parser_module.cpp.i
.PHONY : src/frontend/parser/parser_module.i

# target to preprocess a source file
src/frontend/parser/parser_module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/parser/parser_module.cpp.i
.PHONY : src/frontend/parser/parser_module.cpp.i

src/frontend/parser/parser_module.s: src/frontend/parser/parser_module.cpp.s
.PHONY : src/frontend/parser/parser_module.s

# target to generate assembly for a file
src/frontend/parser/parser_module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/parser/parser_module.cpp.s
.PHONY : src/frontend/parser/parser_module.cpp.s

src/frontend/parser/parser_stmt.o: src/frontend/parser/parser_stmt.cpp.o
.PHONY : src/frontend/parser/parser_stmt.o

# target to build an object file
src/frontend/parser/parser_stmt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/parser/parser_stmt.cpp.o
.PHONY : src/frontend/parser/parser_stmt.cpp.o

src/frontend/parser/parser_stmt.i: src/frontend/parser/parser_stmt.cpp.i
.PHONY : src/frontend/parser/parser_stmt.i

# target to preprocess a source file
src/frontend/parser/parser_stmt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/parser/parser_stmt.cpp.i
.PHONY : src/frontend/parser/parser_stmt.cpp.i

src/frontend/parser/parser_stmt.s: src/frontend/parser/parser_stmt.cpp.s
.PHONY : src/frontend/parser/parser_stmt.s

# target to generate assembly for a file
src/frontend/parser/parser_stmt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/parser/parser_stmt.cpp.s
.PHONY : src/frontend/parser/parser_stmt.cpp.s

src/frontend/types/checking/auto_impl.o: src/frontend/types/checking/auto_impl.cpp.o
.PHONY : src/frontend/types/checking/auto_impl.o

# target to build an object file
src/frontend/types/checking/auto_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/auto_impl.cpp.o
.PHONY : src/frontend/types/checking/auto_impl.cpp.o

src/frontend/types/checking/auto_impl.i: src/frontend/types/checking/auto_impl.cpp.i
.PHONY : src/frontend/types/checking/auto_impl.i

# target to preprocess a source file
src/frontend/types/checking/auto_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/auto_impl.cpp.i
.PHONY : src/frontend/types/checking/auto_impl.cpp.i

src/frontend/types/checking/auto_impl.s: src/frontend/types/checking/auto_impl.cpp.s
.PHONY : src/frontend/types/checking/auto_impl.s

# target to generate assembly for a file
src/frontend/types/checking/auto_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/auto_impl.cpp.s
.PHONY : src/frontend/types/checking/auto_impl.cpp.s

src/frontend/types/checking/call.o: src/frontend/types/checking/call.cpp.o
.PHONY : src/frontend/types/checking/call.o

# target to build an object file
src/frontend/types/checking/call.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/call.cpp.o
.PHONY : src/frontend/types/checking/call.cpp.o

src/frontend/types/checking/call.i: src/frontend/types/checking/call.cpp.i
.PHONY : src/frontend/types/checking/call.i

# target to preprocess a source file
src/frontend/types/checking/call.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/call.cpp.i
.PHONY : src/frontend/types/checking/call.cpp.i

src/frontend/types/checking/call.s: src/frontend/types/checking/call.cpp.s
.PHONY : src/frontend/types/checking/call.s

# target to generate assembly for a file
src/frontend/types/checking/call.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/call.cpp.s
.PHONY : src/frontend/types/checking/call.cpp.s

src/frontend/types/checking/decl.o: src/frontend/types/checking/decl.cpp.o
.PHONY : src/frontend/types/checking/decl.o

# target to build an object file
src/frontend/types/checking/decl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/decl.cpp.o
.PHONY : src/frontend/types/checking/decl.cpp.o

src/frontend/types/checking/decl.i: src/frontend/types/checking/decl.cpp.i
.PHONY : src/frontend/types/checking/decl.i

# target to preprocess a source file
src/frontend/types/checking/decl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/decl.cpp.i
.PHONY : src/frontend/types/checking/decl.cpp.i

src/frontend/types/checking/decl.s: src/frontend/types/checking/decl.cpp.s
.PHONY : src/frontend/types/checking/decl.s

# target to generate assembly for a file
src/frontend/types/checking/decl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/decl.cpp.s
.PHONY : src/frontend/types/checking/decl.cpp.s

src/frontend/types/checking/expr.o: src/frontend/types/checking/expr.cpp.o
.PHONY : src/frontend/types/checking/expr.o

# target to build an object file
src/frontend/types/checking/expr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/expr.cpp.o
.PHONY : src/frontend/types/checking/expr.cpp.o

src/frontend/types/checking/expr.i: src/frontend/types/checking/expr.cpp.i
.PHONY : src/frontend/types/checking/expr.i

# target to preprocess a source file
src/frontend/types/checking/expr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/expr.cpp.i
.PHONY : src/frontend/types/checking/expr.cpp.i

src/frontend/types/checking/expr.s: src/frontend/types/checking/expr.cpp.s
.PHONY : src/frontend/types/checking/expr.s

# target to generate assembly for a file
src/frontend/types/checking/expr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/expr.cpp.s
.PHONY : src/frontend/types/checking/expr.cpp.s

src/frontend/types/checking/generic.o: src/frontend/types/checking/generic.cpp.o
.PHONY : src/frontend/types/checking/generic.o

# target to build an object file
src/frontend/types/checking/generic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/generic.cpp.o
.PHONY : src/frontend/types/checking/generic.cpp.o

src/frontend/types/checking/generic.i: src/frontend/types/checking/generic.cpp.i
.PHONY : src/frontend/types/checking/generic.i

# target to preprocess a source file
src/frontend/types/checking/generic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/generic.cpp.i
.PHONY : src/frontend/types/checking/generic.cpp.i

src/frontend/types/checking/generic.s: src/frontend/types/checking/generic.cpp.s
.PHONY : src/frontend/types/checking/generic.s

# target to generate assembly for a file
src/frontend/types/checking/generic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/generic.cpp.s
.PHONY : src/frontend/types/checking/generic.cpp.s

src/frontend/types/checking/stmt.o: src/frontend/types/checking/stmt.cpp.o
.PHONY : src/frontend/types/checking/stmt.o

# target to build an object file
src/frontend/types/checking/stmt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/stmt.cpp.o
.PHONY : src/frontend/types/checking/stmt.cpp.o

src/frontend/types/checking/stmt.i: src/frontend/types/checking/stmt.cpp.i
.PHONY : src/frontend/types/checking/stmt.i

# target to preprocess a source file
src/frontend/types/checking/stmt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/stmt.cpp.i
.PHONY : src/frontend/types/checking/stmt.cpp.i

src/frontend/types/checking/stmt.s: src/frontend/types/checking/stmt.cpp.s
.PHONY : src/frontend/types/checking/stmt.s

# target to generate assembly for a file
src/frontend/types/checking/stmt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/stmt.cpp.s
.PHONY : src/frontend/types/checking/stmt.cpp.s

src/frontend/types/checking/utils.o: src/frontend/types/checking/utils.cpp.o
.PHONY : src/frontend/types/checking/utils.o

# target to build an object file
src/frontend/types/checking/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/utils.cpp.o
.PHONY : src/frontend/types/checking/utils.cpp.o

src/frontend/types/checking/utils.i: src/frontend/types/checking/utils.cpp.i
.PHONY : src/frontend/types/checking/utils.i

# target to preprocess a source file
src/frontend/types/checking/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/utils.cpp.i
.PHONY : src/frontend/types/checking/utils.cpp.i

src/frontend/types/checking/utils.s: src/frontend/types/checking/utils.cpp.s
.PHONY : src/frontend/types/checking/utils.s

# target to generate assembly for a file
src/frontend/types/checking/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/frontend/types/checking/utils.cpp.s
.PHONY : src/frontend/types/checking/utils.cpp.s

src/hir/lowering/decl.o: src/hir/lowering/decl.cpp.o
.PHONY : src/hir/lowering/decl.o

# target to build an object file
src/hir/lowering/decl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/hir/lowering/decl.cpp.o
.PHONY : src/hir/lowering/decl.cpp.o

src/hir/lowering/decl.i: src/hir/lowering/decl.cpp.i
.PHONY : src/hir/lowering/decl.i

# target to preprocess a source file
src/hir/lowering/decl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/hir/lowering/decl.cpp.i
.PHONY : src/hir/lowering/decl.cpp.i

src/hir/lowering/decl.s: src/hir/lowering/decl.cpp.s
.PHONY : src/hir/lowering/decl.s

# target to generate assembly for a file
src/hir/lowering/decl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/hir/lowering/decl.cpp.s
.PHONY : src/hir/lowering/decl.cpp.s

src/hir/lowering/expr.o: src/hir/lowering/expr.cpp.o
.PHONY : src/hir/lowering/expr.o

# target to build an object file
src/hir/lowering/expr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/hir/lowering/expr.cpp.o
.PHONY : src/hir/lowering/expr.cpp.o

src/hir/lowering/expr.i: src/hir/lowering/expr.cpp.i
.PHONY : src/hir/lowering/expr.i

# target to preprocess a source file
src/hir/lowering/expr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/hir/lowering/expr.cpp.i
.PHONY : src/hir/lowering/expr.cpp.i

src/hir/lowering/expr.s: src/hir/lowering/expr.cpp.s
.PHONY : src/hir/lowering/expr.s

# target to generate assembly for a file
src/hir/lowering/expr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/hir/lowering/expr.cpp.s
.PHONY : src/hir/lowering/expr.cpp.s

src/hir/lowering/impl.o: src/hir/lowering/impl.cpp.o
.PHONY : src/hir/lowering/impl.o

# target to build an object file
src/hir/lowering/impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/hir/lowering/impl.cpp.o
.PHONY : src/hir/lowering/impl.cpp.o

src/hir/lowering/impl.i: src/hir/lowering/impl.cpp.i
.PHONY : src/hir/lowering/impl.i

# target to preprocess a source file
src/hir/lowering/impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/hir/lowering/impl.cpp.i
.PHONY : src/hir/lowering/impl.cpp.i

src/hir/lowering/impl.s: src/hir/lowering/impl.cpp.s
.PHONY : src/hir/lowering/impl.s

# target to generate assembly for a file
src/hir/lowering/impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/hir/lowering/impl.cpp.s
.PHONY : src/hir/lowering/impl.cpp.s

src/hir/lowering/stmt.o: src/hir/lowering/stmt.cpp.o
.PHONY : src/hir/lowering/stmt.o

# target to build an object file
src/hir/lowering/stmt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/hir/lowering/stmt.cpp.o
.PHONY : src/hir/lowering/stmt.cpp.o

src/hir/lowering/stmt.i: src/hir/lowering/stmt.cpp.i
.PHONY : src/hir/lowering/stmt.i

# target to preprocess a source file
src/hir/lowering/stmt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/hir/lowering/stmt.cpp.i
.PHONY : src/hir/lowering/stmt.cpp.i

src/hir/lowering/stmt.s: src/hir/lowering/stmt.cpp.s
.PHONY : src/hir/lowering/stmt.s

# target to generate assembly for a file
src/hir/lowering/stmt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/hir/lowering/stmt.cpp.s
.PHONY : src/hir/lowering/stmt.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mir/lowering/expr_basic.o: src/mir/lowering/expr_basic.cpp.o
.PHONY : src/mir/lowering/expr_basic.o

# target to build an object file
src/mir/lowering/expr_basic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/expr_basic.cpp.o
.PHONY : src/mir/lowering/expr_basic.cpp.o

src/mir/lowering/expr_basic.i: src/mir/lowering/expr_basic.cpp.i
.PHONY : src/mir/lowering/expr_basic.i

# target to preprocess a source file
src/mir/lowering/expr_basic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/expr_basic.cpp.i
.PHONY : src/mir/lowering/expr_basic.cpp.i

src/mir/lowering/expr_basic.s: src/mir/lowering/expr_basic.cpp.s
.PHONY : src/mir/lowering/expr_basic.s

# target to generate assembly for a file
src/mir/lowering/expr_basic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/expr_basic.cpp.s
.PHONY : src/mir/lowering/expr_basic.cpp.s

src/mir/lowering/expr_call.o: src/mir/lowering/expr_call.cpp.o
.PHONY : src/mir/lowering/expr_call.o

# target to build an object file
src/mir/lowering/expr_call.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/expr_call.cpp.o
.PHONY : src/mir/lowering/expr_call.cpp.o

src/mir/lowering/expr_call.i: src/mir/lowering/expr_call.cpp.i
.PHONY : src/mir/lowering/expr_call.i

# target to preprocess a source file
src/mir/lowering/expr_call.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/expr_call.cpp.i
.PHONY : src/mir/lowering/expr_call.cpp.i

src/mir/lowering/expr_call.s: src/mir/lowering/expr_call.cpp.s
.PHONY : src/mir/lowering/expr_call.s

# target to generate assembly for a file
src/mir/lowering/expr_call.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/expr_call.cpp.s
.PHONY : src/mir/lowering/expr_call.cpp.s

src/mir/lowering/expr_ops.o: src/mir/lowering/expr_ops.cpp.o
.PHONY : src/mir/lowering/expr_ops.o

# target to build an object file
src/mir/lowering/expr_ops.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/expr_ops.cpp.o
.PHONY : src/mir/lowering/expr_ops.cpp.o

src/mir/lowering/expr_ops.i: src/mir/lowering/expr_ops.cpp.i
.PHONY : src/mir/lowering/expr_ops.i

# target to preprocess a source file
src/mir/lowering/expr_ops.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/expr_ops.cpp.i
.PHONY : src/mir/lowering/expr_ops.cpp.i

src/mir/lowering/expr_ops.s: src/mir/lowering/expr_ops.cpp.s
.PHONY : src/mir/lowering/expr_ops.s

# target to generate assembly for a file
src/mir/lowering/expr_ops.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/expr_ops.cpp.s
.PHONY : src/mir/lowering/expr_ops.cpp.s

src/mir/lowering/impl.o: src/mir/lowering/impl.cpp.o
.PHONY : src/mir/lowering/impl.o

# target to build an object file
src/mir/lowering/impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/impl.cpp.o
.PHONY : src/mir/lowering/impl.cpp.o

src/mir/lowering/impl.i: src/mir/lowering/impl.cpp.i
.PHONY : src/mir/lowering/impl.i

# target to preprocess a source file
src/mir/lowering/impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/impl.cpp.i
.PHONY : src/mir/lowering/impl.cpp.i

src/mir/lowering/impl.s: src/mir/lowering/impl.cpp.s
.PHONY : src/mir/lowering/impl.s

# target to generate assembly for a file
src/mir/lowering/impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/impl.cpp.s
.PHONY : src/mir/lowering/impl.cpp.s

src/mir/lowering/monomorphization_impl.o: src/mir/lowering/monomorphization_impl.cpp.o
.PHONY : src/mir/lowering/monomorphization_impl.o

# target to build an object file
src/mir/lowering/monomorphization_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/monomorphization_impl.cpp.o
.PHONY : src/mir/lowering/monomorphization_impl.cpp.o

src/mir/lowering/monomorphization_impl.i: src/mir/lowering/monomorphization_impl.cpp.i
.PHONY : src/mir/lowering/monomorphization_impl.i

# target to preprocess a source file
src/mir/lowering/monomorphization_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/monomorphization_impl.cpp.i
.PHONY : src/mir/lowering/monomorphization_impl.cpp.i

src/mir/lowering/monomorphization_impl.s: src/mir/lowering/monomorphization_impl.cpp.s
.PHONY : src/mir/lowering/monomorphization_impl.s

# target to generate assembly for a file
src/mir/lowering/monomorphization_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/monomorphization_impl.cpp.s
.PHONY : src/mir/lowering/monomorphization_impl.cpp.s

src/mir/lowering/stmt.o: src/mir/lowering/stmt.cpp.o
.PHONY : src/mir/lowering/stmt.o

# target to build an object file
src/mir/lowering/stmt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/stmt.cpp.o
.PHONY : src/mir/lowering/stmt.cpp.o

src/mir/lowering/stmt.i: src/mir/lowering/stmt.cpp.i
.PHONY : src/mir/lowering/stmt.i

# target to preprocess a source file
src/mir/lowering/stmt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/stmt.cpp.i
.PHONY : src/mir/lowering/stmt.cpp.i

src/mir/lowering/stmt.s: src/mir/lowering/stmt.cpp.s
.PHONY : src/mir/lowering/stmt.s

# target to generate assembly for a file
src/mir/lowering/stmt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/lowering/stmt.cpp.s
.PHONY : src/mir/lowering/stmt.cpp.s

src/mir/optimizations/optimization_pipeline.o: src/mir/optimizations/optimization_pipeline.cpp.o
.PHONY : src/mir/optimizations/optimization_pipeline.o

# target to build an object file
src/mir/optimizations/optimization_pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/optimizations/optimization_pipeline.cpp.o
.PHONY : src/mir/optimizations/optimization_pipeline.cpp.o

src/mir/optimizations/optimization_pipeline.i: src/mir/optimizations/optimization_pipeline.cpp.i
.PHONY : src/mir/optimizations/optimization_pipeline.i

# target to preprocess a source file
src/mir/optimizations/optimization_pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/optimizations/optimization_pipeline.cpp.i
.PHONY : src/mir/optimizations/optimization_pipeline.cpp.i

src/mir/optimizations/optimization_pipeline.s: src/mir/optimizations/optimization_pipeline.cpp.s
.PHONY : src/mir/optimizations/optimization_pipeline.s

# target to generate assembly for a file
src/mir/optimizations/optimization_pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/mir/optimizations/optimization_pipeline.cpp.s
.PHONY : src/mir/optimizations/optimization_pipeline.cpp.s

src/module/resolver.o: src/module/resolver.cpp.o
.PHONY : src/module/resolver.o

# target to build an object file
src/module/resolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/module/resolver.cpp.o
.PHONY : src/module/resolver.cpp.o

src/module/resolver.i: src/module/resolver.cpp.i
.PHONY : src/module/resolver.i

# target to preprocess a source file
src/module/resolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/module/resolver.cpp.i
.PHONY : src/module/resolver.cpp.i

src/module/resolver.s: src/module/resolver.cpp.s
.PHONY : src/module/resolver.s

# target to generate assembly for a file
src/module/resolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/module/resolver.cpp.s
.PHONY : src/module/resolver.cpp.s

src/preprocessor/import.o: src/preprocessor/import.cpp.o
.PHONY : src/preprocessor/import.o

# target to build an object file
src/preprocessor/import.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/preprocessor/import.cpp.o
.PHONY : src/preprocessor/import.cpp.o

src/preprocessor/import.i: src/preprocessor/import.cpp.i
.PHONY : src/preprocessor/import.i

# target to preprocess a source file
src/preprocessor/import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/preprocessor/import.cpp.i
.PHONY : src/preprocessor/import.cpp.i

src/preprocessor/import.s: src/preprocessor/import.cpp.s
.PHONY : src/preprocessor/import.s

# target to generate assembly for a file
src/preprocessor/import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm.dir/build.make CMakeFiles/cm.dir/src/preprocessor/import.cpp.s
.PHONY : src/preprocessor/import.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... acc_gen"
	@echo "... cm_runtime"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... cm"
	@echo "... src/codegen/common/runtime_functions.o"
	@echo "... src/codegen/common/runtime_functions.i"
	@echo "... src/codegen/common/runtime_functions.s"
	@echo "... src/codegen/common/type_converter.o"
	@echo "... src/codegen/common/type_converter.i"
	@echo "... src/codegen/common/type_converter.s"
	@echo "... src/codegen/js/codegen.o"
	@echo "... src/codegen/js/codegen.i"
	@echo "... src/codegen/js/codegen.s"
	@echo "... src/codegen/js/control_flow.o"
	@echo "... src/codegen/js/control_flow.i"
	@echo "... src/codegen/js/control_flow.s"
	@echo "... src/codegen/js/emit_expressions.o"
	@echo "... src/codegen/js/emit_expressions.i"
	@echo "... src/codegen/js/emit_expressions.s"
	@echo "... src/codegen/js/emit_statements.o"
	@echo "... src/codegen/js/emit_statements.i"
	@echo "... src/codegen/js/emit_statements.s"
	@echo "... src/codegen/llvm/core/context.o"
	@echo "... src/codegen/llvm/core/context.i"
	@echo "... src/codegen/llvm/core/context.s"
	@echo "... src/codegen/llvm/core/interface.o"
	@echo "... src/codegen/llvm/core/interface.i"
	@echo "... src/codegen/llvm/core/interface.s"
	@echo "... src/codegen/llvm/core/intrinsics.o"
	@echo "... src/codegen/llvm/core/intrinsics.i"
	@echo "... src/codegen/llvm/core/intrinsics.s"
	@echo "... src/codegen/llvm/core/mir_to_llvm.o"
	@echo "... src/codegen/llvm/core/mir_to_llvm.i"
	@echo "... src/codegen/llvm/core/mir_to_llvm.s"
	@echo "... src/codegen/llvm/core/operators.o"
	@echo "... src/codegen/llvm/core/operators.i"
	@echo "... src/codegen/llvm/core/operators.s"
	@echo "... src/codegen/llvm/core/print_codegen.o"
	@echo "... src/codegen/llvm/core/print_codegen.i"
	@echo "... src/codegen/llvm/core/print_codegen.s"
	@echo "... src/codegen/llvm/core/terminator.o"
	@echo "... src/codegen/llvm/core/terminator.i"
	@echo "... src/codegen/llvm/core/terminator.s"
	@echo "... src/codegen/llvm/core/types.o"
	@echo "... src/codegen/llvm/core/types.i"
	@echo "... src/codegen/llvm/core/types.s"
	@echo "... src/codegen/llvm/core/utils.o"
	@echo "... src/codegen/llvm/core/utils.i"
	@echo "... src/codegen/llvm/core/utils.s"
	@echo "... src/codegen/llvm/native/codegen.o"
	@echo "... src/codegen/llvm/native/codegen.i"
	@echo "... src/codegen/llvm/native/codegen.s"
	@echo "... src/codegen/llvm/native/target.o"
	@echo "... src/codegen/llvm/native/target.i"
	@echo "... src/codegen/llvm/native/target.s"
	@echo "... src/codegen/llvm/optimizations/inst_combine/inst_combiner.o"
	@echo "... src/codegen/llvm/optimizations/inst_combine/inst_combiner.i"
	@echo "... src/codegen/llvm/optimizations/inst_combine/inst_combiner.s"
	@echo "... src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.o"
	@echo "... src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.i"
	@echo "... src/codegen/llvm/optimizations/loop_unrolling/loop_unroller.s"
	@echo "... src/codegen/llvm/optimizations/optimization_manager.o"
	@echo "... src/codegen/llvm/optimizations/optimization_manager.i"
	@echo "... src/codegen/llvm/optimizations/optimization_manager.s"
	@echo "... src/codegen/llvm/optimizations/peephole/peephole_optimizer.o"
	@echo "... src/codegen/llvm/optimizations/peephole/peephole_optimizer.i"
	@echo "... src/codegen/llvm/optimizations/peephole/peephole_optimizer.s"
	@echo "... src/codegen/llvm/optimizations/vectorization/vectorizer.o"
	@echo "... src/codegen/llvm/optimizations/vectorization/vectorizer.i"
	@echo "... src/codegen/llvm/optimizations/vectorization/vectorizer.s"
	@echo "... src/frontend/lexer/token.o"
	@echo "... src/frontend/lexer/token.i"
	@echo "... src/frontend/lexer/token.s"
	@echo "... src/frontend/parser/parser_expr.o"
	@echo "... src/frontend/parser/parser_expr.i"
	@echo "... src/frontend/parser/parser_expr.s"
	@echo "... src/frontend/parser/parser_module.o"
	@echo "... src/frontend/parser/parser_module.i"
	@echo "... src/frontend/parser/parser_module.s"
	@echo "... src/frontend/parser/parser_stmt.o"
	@echo "... src/frontend/parser/parser_stmt.i"
	@echo "... src/frontend/parser/parser_stmt.s"
	@echo "... src/frontend/types/checking/auto_impl.o"
	@echo "... src/frontend/types/checking/auto_impl.i"
	@echo "... src/frontend/types/checking/auto_impl.s"
	@echo "... src/frontend/types/checking/call.o"
	@echo "... src/frontend/types/checking/call.i"
	@echo "... src/frontend/types/checking/call.s"
	@echo "... src/frontend/types/checking/decl.o"
	@echo "... src/frontend/types/checking/decl.i"
	@echo "... src/frontend/types/checking/decl.s"
	@echo "... src/frontend/types/checking/expr.o"
	@echo "... src/frontend/types/checking/expr.i"
	@echo "... src/frontend/types/checking/expr.s"
	@echo "... src/frontend/types/checking/generic.o"
	@echo "... src/frontend/types/checking/generic.i"
	@echo "... src/frontend/types/checking/generic.s"
	@echo "... src/frontend/types/checking/stmt.o"
	@echo "... src/frontend/types/checking/stmt.i"
	@echo "... src/frontend/types/checking/stmt.s"
	@echo "... src/frontend/types/checking/utils.o"
	@echo "... src/frontend/types/checking/utils.i"
	@echo "... src/frontend/types/checking/utils.s"
	@echo "... src/hir/lowering/decl.o"
	@echo "... src/hir/lowering/decl.i"
	@echo "... src/hir/lowering/decl.s"
	@echo "... src/hir/lowering/expr.o"
	@echo "... src/hir/lowering/expr.i"
	@echo "... src/hir/lowering/expr.s"
	@echo "... src/hir/lowering/impl.o"
	@echo "... src/hir/lowering/impl.i"
	@echo "... src/hir/lowering/impl.s"
	@echo "... src/hir/lowering/stmt.o"
	@echo "... src/hir/lowering/stmt.i"
	@echo "... src/hir/lowering/stmt.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mir/lowering/expr_basic.o"
	@echo "... src/mir/lowering/expr_basic.i"
	@echo "... src/mir/lowering/expr_basic.s"
	@echo "... src/mir/lowering/expr_call.o"
	@echo "... src/mir/lowering/expr_call.i"
	@echo "... src/mir/lowering/expr_call.s"
	@echo "... src/mir/lowering/expr_ops.o"
	@echo "... src/mir/lowering/expr_ops.i"
	@echo "... src/mir/lowering/expr_ops.s"
	@echo "... src/mir/lowering/impl.o"
	@echo "... src/mir/lowering/impl.i"
	@echo "... src/mir/lowering/impl.s"
	@echo "... src/mir/lowering/monomorphization_impl.o"
	@echo "... src/mir/lowering/monomorphization_impl.i"
	@echo "... src/mir/lowering/monomorphization_impl.s"
	@echo "... src/mir/lowering/stmt.o"
	@echo "... src/mir/lowering/stmt.i"
	@echo "... src/mir/lowering/stmt.s"
	@echo "... src/mir/optimizations/optimization_pipeline.o"
	@echo "... src/mir/optimizations/optimization_pipeline.i"
	@echo "... src/mir/optimizations/optimization_pipeline.s"
	@echo "... src/module/resolver.o"
	@echo "... src/module/resolver.i"
	@echo "... src/module/resolver.s"
	@echo "... src/preprocessor/import.o"
	@echo "... src/preprocessor/import.i"
	@echo "... src/preprocessor/import.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

