#include "codegen.hpp"

#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <sstream>

namespace cm::codegen::sv {

SVCodeGen::SVCodeGen(const SVCodeGenOptions& options) : options_(options) {}

// === 型マッピング ===

std::string SVCodeGen::mapType(const hir::TypePtr& type) const {
    if (!type)
        return "logic";

    switch (type->kind) {
        case hir::TypeKind::Bool:
            return "logic";
        case hir::TypeKind::Tiny:
            return "logic signed [7:0]";
        case hir::TypeKind::UTiny:
            return "logic [7:0]";
        case hir::TypeKind::Short:
            return "logic signed [15:0]";
        case hir::TypeKind::UShort:
            return "logic [15:0]";
        case hir::TypeKind::Int:
            return "logic signed [31:0]";
        case hir::TypeKind::UInt:
            return "logic [31:0]";
        case hir::TypeKind::Long:
            return "logic signed [63:0]";
        case hir::TypeKind::ULong:
            return "logic [63:0]";
        case hir::TypeKind::ISize:
            return "logic signed [63:0]";
        case hir::TypeKind::USize:
            return "logic [63:0]";
        // SV固有型
        case hir::TypeKind::Posedge:
        case hir::TypeKind::Negedge:
            return "logic";  // クロック/リセット信号は1bit
        case hir::TypeKind::Wire:
        case hir::TypeKind::Reg:
            // element_typeがあればそれを使用
            if (type->element_type)
                return mapType(type->element_type);
            return "logic [31:0]";
        default:
            return "logic [31:0]";  // デフォルトは32bit
    }
}

int SVCodeGen::getBitWidth(const hir::TypePtr& type) const {
    if (!type)
        return 32;

    switch (type->kind) {
        case hir::TypeKind::Bool:
            return 1;
        case hir::TypeKind::Tiny:
        case hir::TypeKind::UTiny:
            return 8;
        case hir::TypeKind::Short:
        case hir::TypeKind::UShort:
            return 16;
        case hir::TypeKind::Int:
        case hir::TypeKind::UInt:
            return 32;
        case hir::TypeKind::Long:
        case hir::TypeKind::ULong:
        case hir::TypeKind::ISize:
        case hir::TypeKind::USize:
            return 64;
        // SV固有型
        case hir::TypeKind::Posedge:
        case hir::TypeKind::Negedge:
            return 1;  // クロック/リセット信号は1bit
        case hir::TypeKind::Wire:
        case hir::TypeKind::Reg:
            if (type->element_type)
                return getBitWidth(type->element_type);
            return 32;
        default:
            return 32;
    }
}

// === コード出力ヘルパー ===

void SVCodeGen::emit(const std::string& code) {
    append(code);
}

void SVCodeGen::emitLine(const std::string& code) {
    append_line(indent() + code);
}

void SVCodeGen::emitIndented(const std::string& code) {
    append(indent() + code);
}

void SVCodeGen::increaseIndent() {
    indent_level_++;
}

void SVCodeGen::decreaseIndent() {
    if (indent_level_ > 0)
        indent_level_--;
}

std::string SVCodeGen::indent() const {
    return std::string(indent_level_ * options_.indentSpaces, ' ');
}

// === ファイルヘッダー ===

void SVCodeGen::emitFileHeader() {
    emitLine("// SystemVerilog generated by Cm compiler");
    emitLine("// ターゲット: SystemVerilog IEEE 1800-2017");
    emitLine("`timescale 1ns / 1ps");
    append_line("");
}

// === モジュール生成 ===

void SVCodeGen::emitPortList(const std::vector<SVPort>& ports) {
    if (ports.empty()) {
        emitLine("();");
        return;
    }

    emitLine("(");
    increaseIndent();
    for (size_t i = 0; i < ports.size(); i++) {
        const auto& port = ports[i];
        std::string dir;
        switch (port.direction) {
            case SVPort::Input:
                dir = "input ";
                break;
            case SVPort::Output:
                dir = "output ";
                break;
            case SVPort::InOut:
                dir = "inout ";
                break;
        }
        std::string line = dir + port.sv_type + " " + port.name;
        if (i < ports.size() - 1) {
            line += ",";
        }
        emitLine(line);
    }
    decreaseIndent();
    emitLine(");");
}

void SVCodeGen::emitModule(const SVModule& mod) {
    // module宣言
    emitIndented("module " + mod.name + " ");

    // ポートリスト
    emitPortList(mod.ports);
    append_line("");

    increaseIndent();

    // parameter宣言
    for (const auto& param : mod.parameters) {
        emitLine(param);
    }
    if (!mod.parameters.empty()) {
        append_line("");
    }

    // 内部ワイヤ宣言
    for (const auto& wire : mod.wire_declarations) {
        emitLine(wire);
    }

    // 内部レジスタ宣言
    for (const auto& reg : mod.reg_declarations) {
        emitLine(reg);
    }

    if (!mod.wire_declarations.empty() || !mod.reg_declarations.empty()) {
        append_line("");
    }

    // always_ff ブロック
    for (const auto& block : mod.always_ff_blocks) {
        emit(block);
        append_line("");
    }

    // always_comb ブロック
    for (const auto& block : mod.always_comb_blocks) {
        emit(block);
        append_line("");
    }

    // assign 文
    for (const auto& stmt : mod.assign_statements) {
        emitLine(stmt);
    }

    decreaseIndent();
    emitLine("endmodule");
    append_line("");
}

// === 定数リテラル ===

std::string SVCodeGen::emitConstant(const mir::MirConstant& constant, const hir::TypePtr& type) {
    int width = getBitWidth(type);

    if (std::holds_alternative<bool>(constant.value)) {
        return std::get<bool>(constant.value) ? "1'b1" : "1'b0";
    }

    if (std::holds_alternative<int64_t>(constant.value)) {
        int64_t val = std::get<int64_t>(constant.value);

        // SV幅付きリテラルの場合、元のベース形式を保持して出力
        if (constant.bit_width > 0 && !constant.bit_original.empty()) {
            // 元の表記をそのまま使用: N'bXXX, N'hXXX, N'dXXX
            return std::to_string(constant.bit_width) + "'" + constant.bit_base +
                   constant.bit_original;
        }

        // SV幅付きリテラル（元表記がない場合）またはデフォルト
        int effective_width = (constant.bit_width > 0) ? constant.bit_width : width;
        // signed型かどうか判定
        bool is_signed =
            type && (type->kind == hir::TypeKind::Int || type->kind == hir::TypeKind::Short ||
                     type->kind == hir::TypeKind::Tiny || type->kind == hir::TypeKind::Long);
        std::string prefix = std::to_string(effective_width) + (is_signed ? "'sd" : "'d");
        if (val < 0) {
            return "-" + prefix + std::to_string(-val);
        }
        return prefix + std::to_string(val);
    }

    if (std::holds_alternative<std::monostate>(constant.value)) {
        return std::to_string(width) + "'d0";
    }

    return "0";
}

// === Place（左辺値）生成 ===

std::string SVCodeGen::emitPlace(const mir::MirPlace& place, const mir::MirFunction& func) {
    // ローカル変数名を取得
    std::string name;
    if (place.local < func.locals.size()) {
        name = func.locals[place.local].name;
        if (name.empty()) {
            name = "_" + std::to_string(place.local);
        }
    } else {
        name = "_" + std::to_string(place.local);
    }

    // self. プレフィックスを除去（SVでは不要）
    if (name.find("self.") == 0) {
        name = name.substr(5);
    }

    // フィールドアクセスの投影を適用
    for (const auto& proj : place.projections) {
        if (proj.kind == mir::ProjectionKind::Field) {
            name += "[" + std::to_string(proj.field_id) + "]";
        }
    }

    return name;
}

// === オペランド生成 ===

std::string SVCodeGen::emitOperand(const mir::MirOperand& operand, const mir::MirFunction& func) {
    switch (operand.kind) {
        case mir::MirOperand::Move:
        case mir::MirOperand::Copy: {
            // data は variant<MirPlace, MirConstant, string>
            const auto& place = std::get<mir::MirPlace>(operand.data);
            return emitPlace(place, func);
        }
        case mir::MirOperand::Constant: {
            const auto& constant = std::get<mir::MirConstant>(operand.data);
            return emitConstant(constant, operand.type);
        }
        default:
            return "/* unknown operand */";
    }
}

// === 右辺値生成 ===

std::string SVCodeGen::emitRvalue(const mir::MirRvalue& rvalue, const mir::MirFunction& func) {
    switch (rvalue.kind) {
        case mir::MirRvalue::Use: {
            const auto& use_data = std::get<mir::MirRvalue::UseData>(rvalue.data);
            if (use_data.operand) {
                return emitOperand(*use_data.operand, func);
            }
            return "0";
        }

        case mir::MirRvalue::BinaryOp: {
            const auto& bin = std::get<mir::MirRvalue::BinaryOpData>(rvalue.data);
            std::string lhs = bin.lhs ? emitOperand(*bin.lhs, func) : "0";
            std::string rhs = bin.rhs ? emitOperand(*bin.rhs, func) : "0";
            std::string op;
            switch (bin.op) {
                case mir::MirBinaryOp::Add:
                    op = " + ";
                    break;
                case mir::MirBinaryOp::Sub:
                    op = " - ";
                    break;
                case mir::MirBinaryOp::Mul:
                    op = " * ";
                    break;
                case mir::MirBinaryOp::Div:
                    op = " / ";
                    break;
                case mir::MirBinaryOp::Mod:
                    op = " % ";
                    break;
                case mir::MirBinaryOp::BitAnd:
                    op = " & ";
                    break;
                case mir::MirBinaryOp::BitOr:
                    op = " | ";
                    break;
                case mir::MirBinaryOp::BitXor:
                    op = " ^ ";
                    break;
                case mir::MirBinaryOp::Shl:
                    op = " << ";
                    break;
                case mir::MirBinaryOp::Shr:
                    op = " >> ";
                    break;
                case mir::MirBinaryOp::Eq:
                    op = " == ";
                    break;
                case mir::MirBinaryOp::Ne:
                    op = " != ";
                    break;
                case mir::MirBinaryOp::Lt:
                    op = " < ";
                    break;
                case mir::MirBinaryOp::Le:
                    op = " <= ";
                    break;
                case mir::MirBinaryOp::Gt:
                    op = " > ";
                    break;
                case mir::MirBinaryOp::Ge:
                    op = " >= ";
                    break;
                case mir::MirBinaryOp::And:
                    op = " && ";
                    break;
                case mir::MirBinaryOp::Or:
                    op = " || ";
                    break;
                default:
                    op = " /* unknown op */ ";
                    break;
            }
            return lhs + op + rhs;
        }

        case mir::MirRvalue::UnaryOp: {
            const auto& unary = std::get<mir::MirRvalue::UnaryOpData>(rvalue.data);
            std::string operand_str = unary.operand ? emitOperand(*unary.operand, func) : "0";
            switch (unary.op) {
                case mir::MirUnaryOp::Neg:
                    return "-" + operand_str;
                case mir::MirUnaryOp::Not:
                    return "!" + operand_str;
                case mir::MirUnaryOp::BitNot:
                    return "~" + operand_str;
                default:
                    return operand_str;
            }
        }

        case mir::MirRvalue::Cast: {
            const auto& cast = std::get<mir::MirRvalue::CastData>(rvalue.data);
            if (cast.operand) {
                return emitOperand(*cast.operand, func);
            }
            return "0";
        }

        default:
            return "/* unsupported rvalue */";
    }
}

// === 文の生成 ===

std::string SVCodeGen::emitStatement(const mir::MirStatement& stmt, const mir::MirFunction& func) {
    switch (stmt.kind) {
        case mir::MirStatement::Assign: {
            const auto& assign = std::get<mir::MirStatement::AssignData>(stmt.data);
            std::string lhs = emitPlace(assign.place, func);
            std::string rhs = assign.rvalue ? emitRvalue(*assign.rvalue, func) : "0";
            // async func内またはposedge/negedge型パラメータを持つ関数はノンブロッキング代入
            bool use_nonblocking = func.is_async;
            if (!use_nonblocking) {
                for (const auto& local : func.locals) {
                    if (local.type && (local.type->kind == hir::TypeKind::Posedge ||
                                       local.type->kind == hir::TypeKind::Negedge)) {
                        use_nonblocking = true;
                        break;
                    }
                }
            }
            if (use_nonblocking) {
                return lhs + " <= " + rhs + ";";
            } else {
                return lhs + " = " + rhs + ";";
            }
        }
        case mir::MirStatement::StorageLive:
        case mir::MirStatement::StorageDead:
        case mir::MirStatement::Nop:
            return "";  // SVでは不要
        default:
            return "// unsupported statement";
    }
}

// === 基本ブロック生成 ===

std::string SVCodeGen::emitBlock(const mir::BasicBlock& block, const mir::MirFunction& func) {
    std::ostringstream ss;
    for (const auto& stmt : block.statements) {
        if (!stmt)
            continue;
        std::string line = emitStatement(*stmt, func);
        if (options_.verbose)
            if (!line.empty()) {
                ss << indent() << line << "\n";
            }
    }
    return ss.str();
}

// === MIR解析: 関数 → always ブロック ===

void SVCodeGen::analyzeFunction(const mir::MirFunction& func, SVModule& mod) {
    // main関数はスキップ（ハードウェアにmainはない）
    if (func.name == "main")
        return;

    // ローカル変数を内部ワイヤ/レジスタとして宣言
    // （ポートと名前が衝突する変数は除外）
    std::set<std::string> port_names;
    for (const auto& port : mod.ports) {
        port_names.insert(port.name);
    }
    for (const auto& local : func.locals) {
        std::string name = local.name;
        if (name.empty() || name == "_0")
            continue;  // 戻り値用
        // 不正なSV識別子をスキップ（@return等）
        if (name.find('@') != std::string::npos)
            continue;
        // self.プレフィックスを除去
        if (name.find("self.") == 0)
            name = name.substr(5);
        // ポートと名前が衝突する場合はスキップ
        if (port_names.count(name))
            continue;
        // 既に登録済みの宣言もスキップ
        std::string decl = mapType(local.type) + " " + name + ";";
        bool already_declared = false;
        for (const auto& existing : mod.reg_declarations) {
            if (existing == decl) {
                already_declared = true;
                break;
            }
        }
        if (!already_declared) {
            mod.reg_declarations.push_back(decl);
        }
    }

    std::ostringstream block_ss;

    // 関数名コメントを追加
    block_ss << indent() << "// " << func.name << "\n";

    // SV固有型: posedge/negedge型パラメータの検出
    std::string edge_type;   // "posedge" or "negedge"
    std::string edge_clock;  // クロック信号名
    bool has_explicit_edge = false;

    for (const auto& local : func.locals) {
        if (local.type && local.type->kind == hir::TypeKind::Posedge) {
            edge_type = "posedge";
            edge_clock = local.name;
            has_explicit_edge = true;
            break;
        }
        if (local.type && local.type->kind == hir::TypeKind::Negedge) {
            edge_type = "negedge";
            edge_clock = local.name;
            has_explicit_edge = true;
            break;
        }
    }

    if (has_explicit_edge) {
        // 明示的なposedge/negedge型パラメータ → always_ff
        block_ss << indent() << "always_ff @(" << edge_type << " " << edge_clock << ") begin\n";
    } else if (func.is_async) {
        // Phase 4: マルチクロックドメイン対応（後方互換: async func）
        std::string clock_name = "clk";
        for (const auto& attr : func.attributes) {
            std::string prefix1 = "sv::clock_domain(";
            std::string prefix2 = "verilog::clock_domain(";
            if (attr.find(prefix1) == 0 && attr.back() == ')') {
                clock_name = attr.substr(prefix1.size(), attr.size() - prefix1.size() - 1);
            } else if (attr.find(prefix2) == 0 && attr.back() == ')') {
                clock_name = attr.substr(prefix2.size(), attr.size() - prefix2.size() - 1);
            }
        }

        for (const auto& attr : func.attributes) {
            if (attr.find("sv::pipeline") != std::string::npos ||
                attr.find("verilog::pipeline") != std::string::npos) {
                block_ss << indent() << "// synthesis attribute: " << attr << "\n";
            }
            if (attr.find("sv::share") != std::string::npos ||
                attr.find("verilog::share") != std::string::npos) {
                block_ss << indent() << "// synthesis attribute: resource sharing enabled\n";
            }
        }

        block_ss << indent() << "always_ff @(posedge " << clock_name << ") begin\n";
    } else {
        block_ss << indent() << "always_comb begin\n";
    }

    increaseIndent();

    // CFG再帰走査でブロックを構造化出力
    // まず一時変数のマッピングを構築（インライン展開用）
    std::map<std::string, std::string> temp_values;
    std::ostringstream raw_ss;
    if (!func.basic_blocks.empty() && func.basic_blocks[0]) {
        std::set<size_t> visited;
        emitBlockRecursive(func, 0, visited, raw_ss);
    }

    // 一時変数のインライン展開処理
    // _tXXXX = expr; の形式を検出し、後続の使用箇所で直接式に置換
    std::istringstream raw_stream(raw_ss.str());
    std::string line;
    std::vector<std::string> lines;
    while (std::getline(raw_stream, line)) {
        lines.push_back(line);
    }

    // Pass 1: 一時変数の値を収集
    for (const auto& l : lines) {
        // インデントを除去して解析
        std::string trimmed = l;
        size_t start = trimmed.find_first_not_of(' ');
        if (start == std::string::npos)
            continue;
        trimmed = trimmed.substr(start);

        // \"_tXXXX = expr;\" または \"_tXXXX <= expr;\" パターンを検出
        if (trimmed.size() > 2 && trimmed[0] == '_' && trimmed[1] == 't' &&
            std::isdigit(trimmed[2])) {
            // ブロッキング代入 (=) を検出
            auto eq_pos = trimmed.find(" = ");
            // ノンブロッキング代入 (<=) を検出
            auto nbeq_pos = trimmed.find(" <= ");
            if (eq_pos != std::string::npos) {
                std::string var_name = trimmed.substr(0, eq_pos);
                std::string value = trimmed.substr(eq_pos + 3);
                if (!value.empty() && value.back() == ';') {
                    value.pop_back();
                }
                temp_values[var_name] = value;
            } else if (nbeq_pos != std::string::npos) {
                std::string var_name = trimmed.substr(0, nbeq_pos);
                std::string value = trimmed.substr(nbeq_pos + 4);
                if (!value.empty() && value.back() == ';') {
                    value.pop_back();
                }
                temp_values[var_name] = value;
            }
        }
    }

    // 一時変数を再帰的に展開する関数
    auto inline_temps = [&temp_values](const std::string& expr) -> std::string {
        std::string result = expr;
        // 最大10回の反復で再帰的に展開
        for (int iter = 0; iter < 10; ++iter) {
            bool changed = false;
            for (const auto& [var, val] : temp_values) {
                size_t pos = 0;
                while ((pos = result.find(var, pos)) != std::string::npos) {
                    // 変数名の境界チェック
                    bool at_start =
                        (pos == 0 || !std::isalnum(result[pos - 1]) && result[pos - 1] != '_');
                    bool at_end = (pos + var.size() >= result.size() ||
                                   (!std::isalnum(result[pos + var.size()]) &&
                                    result[pos + var.size()] != '_'));
                    if (at_start && at_end) {
                        // 値に演算子が含まれる場合は括弧で囲む
                        std::string replacement = val;
                        if (val.find(' ') != std::string::npos &&
                            (pos > 0 || pos + var.size() < result.size())) {
                            // 単純代入の右辺値でなければ括弧付き
                            // ただし代入文の右辺全体なら括弧不要
                            bool is_full_rhs = (pos == 0 && pos + var.size() == result.size());
                            if (!is_full_rhs) {
                                replacement = "(" + val + ")";
                            }
                        }
                        result.replace(pos, var.size(), replacement);
                        changed = true;
                        pos += replacement.size();
                    } else {
                        pos += var.size();
                    }
                }
            }
            if (!changed)
                break;
        }
        return result;
    };

    // Pass 2: 一時変数代入を除外し、残りの文の一時変数をインライン展開
    for (const auto& l : lines) {
        std::string trimmed = l;
        size_t start = trimmed.find_first_not_of(' ');
        if (start == std::string::npos) {
            block_ss << l << "\n";
            continue;
        }
        std::string content = trimmed.substr(start);

        // 一時変数への代入行はスキップ（= と <= の両方対応）
        if (content.size() > 2 && content[0] == '_' && content[1] == 't' &&
            std::isdigit(content[2]) &&
            (content.find(" = ") != std::string::npos ||
             content.find(" <= ") != std::string::npos)) {
            continue;
        }

        // 非一時変数の代入文をインライン展開
        auto eq_pos = content.find(" = ");
        if (eq_pos != std::string::npos) {
            std::string lhs = content.substr(0, eq_pos);
            std::string rhs = content.substr(eq_pos + 3);
            // 末尾セミコロン除去
            if (!rhs.empty() && rhs.back() == ';') {
                rhs.pop_back();
            }
            rhs = inline_temps(rhs);
            block_ss << indent() << lhs << " = " << rhs << ";\n";
        } else if (content.find(" <= ") != std::string::npos) {
            // ノンブロッキング代入のインライン展開
            auto nbeq_pos = content.find(" <= ");
            std::string lhs = content.substr(0, nbeq_pos);
            std::string rhs = content.substr(nbeq_pos + 4);
            if (!rhs.empty() && rhs.back() == ';') {
                rhs.pop_back();
            }
            rhs = inline_temps(rhs);
            block_ss << indent() << lhs << " <= " << rhs << ";\n";
        } else {
            // if/else等の構造制御文でも一時変数を反復的にインライン展開
            std::string expanded = l;
            // 最大10回の反復で多段展開（_t1002 → _t1000 == _t1001 → a == b）
            for (int iter = 0; iter < 10; ++iter) {
                bool changed = false;
                for (const auto& [var, val] : temp_values) {
                    size_t pos = 0;
                    while ((pos = expanded.find(var, pos)) != std::string::npos) {
                        bool at_start = (pos == 0 || (!std::isalnum(expanded[pos - 1]) &&
                                                      expanded[pos - 1] != '_'));
                        bool at_end = (pos + var.size() >= expanded.size() ||
                                       (!std::isalnum(expanded[pos + var.size()]) &&
                                        expanded[pos + var.size()] != '_'));
                        if (at_start && at_end) {
                            expanded.replace(pos, var.size(), val);
                            pos += val.size();
                            changed = true;
                        } else {
                            pos += var.size();
                        }
                    }
                }
                if (!changed)
                    break;
            }
            block_ss << expanded << "\n";
        }
    }

    decreaseIndent();
    block_ss << indent() << "end\n";

    if (has_explicit_edge || func.is_async) {
        mod.always_ff_blocks.push_back(block_ss.str());
    } else {
        mod.always_comb_blocks.push_back(block_ss.str());
    }
}

// === 合流ブロック探索 ===
// 2つの分岐先から辿って最初に共通する後続ブロックIDを探す
size_t SVCodeGen::findMergeBlock(const mir::MirFunction& func, size_t then_block,
                                 size_t else_block) {
    // 各ブランチから到達可能なブロックを収集
    std::set<size_t> then_reachable;
    std::vector<size_t> work = {then_block};
    while (!work.empty()) {
        size_t bid = work.back();
        work.pop_back();
        if (bid >= func.basic_blocks.size() || !func.basic_blocks[bid])
            continue;
        if (!then_reachable.insert(bid).second)
            continue;
        const auto& bb = *func.basic_blocks[bid];
        if (bb.terminator) {
            if (bb.terminator->kind == mir::MirTerminator::Goto) {
                auto& gd = std::get<mir::MirTerminator::GotoData>(bb.terminator->data);
                work.push_back(gd.target);
            } else if (bb.terminator->kind == mir::MirTerminator::SwitchInt) {
                auto& sd = std::get<mir::MirTerminator::SwitchIntData>(bb.terminator->data);
                for (const auto& [val, target] : sd.targets) {
                    work.push_back(target);
                }
                work.push_back(sd.otherwise);
            }
        }
    }

    // elseブランチから辿って最初にthen_reachableに含まれるブロックを探す
    work = {else_block};
    std::set<size_t> visited;
    while (!work.empty()) {
        size_t bid = work.back();
        work.pop_back();
        if (bid >= func.basic_blocks.size() || !func.basic_blocks[bid])
            continue;
        if (!visited.insert(bid).second)
            continue;
        if (then_reachable.count(bid) && bid != then_block && bid != else_block) {
            return bid;  // 合流ブロック発見
        }
        const auto& bb = *func.basic_blocks[bid];
        if (bb.terminator) {
            if (bb.terminator->kind == mir::MirTerminator::Goto) {
                auto& gd = std::get<mir::MirTerminator::GotoData>(bb.terminator->data);
                work.push_back(gd.target);
            }
        }
    }

    return SIZE_MAX;  // 合流ブロックなし
}

// === CFG再帰走査ベースのブロック出力 ===
void SVCodeGen::emitBlockRecursive(const mir::MirFunction& func, size_t block_id,
                                   std::set<size_t>& visited, std::ostringstream& ss,
                                   size_t merge_block) {
    // 既に訪問済み、または合流ブロックに到達した場合は停止
    if (block_id >= func.basic_blocks.size() || !func.basic_blocks[block_id])
        return;
    if (visited.count(block_id))
        return;
    if (block_id == merge_block)
        return;

    visited.insert(block_id);
    const auto& bb = *func.basic_blocks[block_id];

    // ブロック内の文を出力
    for (const auto& stmt : bb.statements) {
        if (!stmt)
            continue;
        std::string line = emitStatement(*stmt, func);
        if (!line.empty()) {
            ss << indent() << line << "\n";
        }
    }

    // ターミネータを処理
    if (bb.terminator) {
        emitTerminator(*bb.terminator, func, visited, ss, merge_block);
    }
}

// === ターミネータのSV変換 ===
void SVCodeGen::emitTerminator(const mir::MirTerminator& term, const mir::MirFunction& func,
                               std::set<size_t>& visited, std::ostringstream& ss,
                               size_t merge_block) {
    switch (term.kind) {
        case mir::MirTerminator::Goto: {
            // 無条件ジャンプ → 後続ブロックをインライン出力
            const auto& gd = std::get<mir::MirTerminator::GotoData>(term.data);
            emitBlockRecursive(func, gd.target, visited, ss, merge_block);
            break;
        }
        case mir::MirTerminator::SwitchInt: {
            // 条件分岐 → if/else begin...end
            const auto& sd = std::get<mir::MirTerminator::SwitchIntData>(term.data);
            std::string cond = sd.discriminant ? emitOperand(*sd.discriminant, func) : "0";

            if (sd.targets.size() == 1) {
                // if (cond == val) ... else ...
                // MIRのSwitchIntは: targets=[(val, then_block)], otherwise=else_block
                size_t then_block = sd.targets[0].second;
                size_t else_block = sd.otherwise;

                // 合流ブロックを探す
                size_t merge = findMergeBlock(func, then_block, else_block);

                // bool分岐の場合、val==0なら否定条件
                bool is_negated = (sd.targets[0].first == 0);

                if (is_negated) {
                    // SwitchInt(cond, [(0, then_block)], otherwise=else_block)
                    // → if (!cond) then_block else else_block
                    // → if (cond) else_block else then_block (反転)
                    ss << indent() << "if (" << cond << ") begin\n";
                    increaseIndent();
                    emitBlockRecursive(func, else_block, visited, ss, merge);
                    decreaseIndent();
                    // else ブロック（空でなければ出力）
                    std::ostringstream else_ss;
                    std::set<size_t> else_visited = visited;
                    increaseIndent();
                    emitBlockRecursive(func, then_block, else_visited, else_ss, merge);
                    decreaseIndent();
                    if (!else_ss.str().empty()) {
                        ss << indent() << "end else begin\n";
                        ss << else_ss.str();
                        visited.insert(else_visited.begin(), else_visited.end());
                    }
                } else {
                    ss << indent() << "if (" << cond << ") begin\n";
                    increaseIndent();
                    emitBlockRecursive(func, then_block, visited, ss, merge);
                    decreaseIndent();
                    std::ostringstream else_ss;
                    std::set<size_t> else_visited = visited;
                    increaseIndent();
                    emitBlockRecursive(func, else_block, else_visited, else_ss, merge);
                    decreaseIndent();
                    if (!else_ss.str().empty()) {
                        ss << indent() << "end else begin\n";
                        ss << else_ss.str();
                        visited.insert(else_visited.begin(), else_visited.end());
                    }
                }
                ss << indent() << "end\n";

                // 合流ブロックを処理
                if (merge != SIZE_MAX) {
                    emitBlockRecursive(func, merge, visited, ss, merge_block);
                }
            } else {
                // 複数ターゲット → case文
                // 全分岐先が合流するブロックを探す（最初の2つから合流点を特定）
                size_t merge = SIZE_MAX;
                if (sd.targets.size() >= 2) {
                    merge = findMergeBlock(func, sd.targets[0].second, sd.targets[1].second);
                }

                ss << indent() << "case (" << cond << ")\n";
                increaseIndent();

                // 各ターゲットのケース
                for (const auto& [val, target] : sd.targets) {
                    ss << indent() << val << ": begin\n";
                    increaseIndent();
                    std::set<size_t> case_visited = visited;
                    emitBlockRecursive(func, target, case_visited, ss, merge);
                    visited.insert(case_visited.begin(), case_visited.end());
                    decreaseIndent();
                    ss << indent() << "end\n";
                }

                // defaultケース (otherwise)
                ss << indent() << "default: begin\n";
                increaseIndent();
                std::set<size_t> default_visited = visited;
                emitBlockRecursive(func, sd.otherwise, default_visited, ss, merge);
                visited.insert(default_visited.begin(), default_visited.end());
                decreaseIndent();
                ss << indent() << "end\n";

                decreaseIndent();
                ss << indent() << "endcase\n";

                // 合流ブロックを処理
                if (merge != SIZE_MAX) {
                    emitBlockRecursive(func, merge, visited, ss, merge_block);
                }
            }
            break;
        }
        case mir::MirTerminator::Return:
        case mir::MirTerminator::Unreachable:
            // SVのalwaysブロック内ではreturnは不要
            break;
        case mir::MirTerminator::Call:
            // 関数呼び出し → Phase 2対応
            break;
    }
}

// === MIR解析: プログラム全体 ===

void SVCodeGen::analyzeMIR(const mir::MirProgram& program) {
    SVModule default_mod;
    default_mod.name = "top";

    // ソースファイル名からモジュール名を推定（SV予約語を回避）
    auto extractBaseName = [](const std::string& path) -> std::string {
        std::string base = path;
        auto slash = base.rfind('/');
        if (slash != std::string::npos)
            base = base.substr(slash + 1);
        auto dot = base.rfind('.');
        if (dot != std::string::npos)
            base = base.substr(0, dot);
        return base;
    };

    // SV予約語リスト（モジュール名として使用不可）
    static const std::set<std::string> sv_reserved = {
        "output",   "input",     "inout",   "module",  "wire",    "reg",     "logic",
        "begin",    "end",       "if",      "else",    "for",     "while",   "case",
        "default",  "assign",    "always",  "initial", "posedge", "negedge", "task",
        "function", "parameter", "integer", "real",    "time",    "event"};

    // ソースファイル名を優先してモジュール名を決定
    if (!options_.sourceFile.empty()) {
        std::string base = extractBaseName(options_.sourceFile);
        if (!base.empty() && sv_reserved.find(base) == sv_reserved.end()) {
            default_mod.name = base;
        } else if (!base.empty()) {
            default_mod.name = base + "_mod";
        }
    } else if (!options_.outputFile.empty()) {
        std::string base = extractBaseName(options_.outputFile);
        if (!base.empty() && sv_reserved.find(base) == sv_reserved.end()) {
            default_mod.name = base;
        } else if (!base.empty()) {
            default_mod.name = base + "_mod";
        }
    }

    // グローバル変数からポートと内部シグナルを生成
    bool has_clk = false;
    bool has_rst = false;
    for (const auto& gv : program.global_vars) {
        if (!gv)
            continue;

        // 属性からポート方向を判定
        bool is_input = false;
        bool is_output = false;
        bool is_inout = false;
        bool is_param = false;
        for (const auto& attr : gv->attributes) {
            if (attr == "input")
                is_input = true;
            if (attr == "output")
                is_output = true;
            if (attr == "inout")
                is_inout = true;
            if (attr == "sv::param" || attr == "verilog::param")
                is_param = true;
        }

        // parameter宣言
        if (is_param) {
            std::string param_decl = "parameter " + mapType(gv->type) + " " + gv->name;
            // 初期値がある場合は付加
            if (gv->init_value) {
                param_decl += " = " + emitConstant(*gv->init_value, gv->type);
            }
            param_decl += ";";
            default_mod.parameters.push_back(param_decl);
            continue;
        }

        // Phase 3: BRAM/LutRAM推論
        bool is_bram = false;
        bool is_lutram = false;
        for (const auto& attr : gv->attributes) {
            if (attr == "sv::bram" || attr == "verilog::bram")
                is_bram = true;
            if (attr == "sv::lutram" || attr == "verilog::lutram")
                is_lutram = true;
        }
        if (is_bram || is_lutram) {
            std::string ram_attr =
                is_bram ? "(* ram_style = \"block\" *) " : "(* ram_style = \"distributed\" *) ";
            std::string ram_decl = ram_attr + mapType(gv->type) + " " + gv->name + ";";
            default_mod.reg_declarations.push_back(ram_decl);
            continue;
        }

        if (is_input) {
            default_mod.ports.push_back(
                {SVPort::Input, gv->name, mapType(gv->type), getBitWidth(gv->type)});
            if (gv->name == "clk")
                has_clk = true;
            if (gv->name == "rst")
                has_rst = true;
        } else if (is_inout) {
            default_mod.ports.push_back(
                {SVPort::InOut, gv->name, mapType(gv->type), getBitWidth(gv->type)});
        } else if (is_output) {
            default_mod.ports.push_back(
                {SVPort::Output, gv->name, mapType(gv->type), getBitWidth(gv->type)});
        } else {
            // 属性なし → 内部レジスタ/ワイヤとして宣言
            default_mod.reg_declarations.push_back(mapType(gv->type) + " " + gv->name + ";");
        }
    }

    // ポートにclk/rstが含まれていない場合、自動追加（async funcがある場合のみ）
    bool has_async = false;
    for (const auto& func : program.functions) {
        if (func && func->is_async) {
            has_async = true;
            break;
        }
    }
    if (has_async && !has_clk) {
        default_mod.ports.insert(default_mod.ports.begin(),
                                 SVPort{SVPort::Input, "clk", "logic", 1});
    }
    if (has_async && !has_rst) {
        default_mod.ports.insert(default_mod.ports.begin() + (has_clk ? 1 : 1),
                                 SVPort{SVPort::Input, "rst", "logic", 1});
    }

    // 各関数を解析
    for (const auto& func : program.functions) {
        if (!func)
            continue;
        analyzeFunction(*func, default_mod);
    }

    modules_.push_back(default_mod);
}

// === メインコンパイル処理 ===

void SVCodeGen::compile(const mir::MirProgram& program) {
    begin_generation();

    // ファイルヘッダー
    emitFileHeader();

    // MIR解析
    analyzeMIR(program);

    // 各モジュールを出力
    for (const auto& mod : modules_) {
        emitModule(mod);
    }

    generated_code_ = end_generation();

    // ファイルに出力
    writeToFile(generated_code_, options_.outputFile);

    if (options_.verbose) {
        std::cout << "✓ SystemVerilog 生成完了: " << options_.outputFile << "\n";
        std::cout << "  行数: " << get_stats().total_lines << "\n";
        std::cout << "  サイズ: " << get_stats().total_bytes << " bytes\n";
    }

    // テストベンチ自動生成（モジュールがあれば）
    if (!modules_.empty()) {
        std::string tb_code = generateTestbench(modules_[0]);
        std::string tb_path = options_.outputFile;
        auto dot = tb_path.rfind('.');
        if (dot != std::string::npos) {
            tb_path = tb_path.substr(0, dot) + "_tb.sv";
        } else {
            tb_path += "_tb.sv";
        }
        writeToFile(tb_code, tb_path);
    }

    // XDC制約出力（ピン属性があれば）
    std::string xdc = generateXDC(program);
    if (!xdc.empty()) {
        std::string xdc_path = options_.outputFile;
        auto dot = xdc_path.rfind('.');
        if (dot != std::string::npos) {
            xdc_path = xdc_path.substr(0, dot) + ".xdc";
        } else {
            xdc_path += ".xdc";
        }
        writeToFile(xdc, xdc_path);
    }
}

// === ファイル出力 ===

void SVCodeGen::writeToFile(const std::string& content, const std::string& path) {
    std::ofstream ofs(path);
    if (!ofs) {
        std::cerr << "エラー: ファイル '" << path << "' を開けません\n";
        return;
    }
    ofs << content;
}

// === テストベンチ自動生成 ===

std::string SVCodeGen::generateTestbench(const SVModule& mod) {
    std::ostringstream ss;

    // ソースファイルから//! test:コメントをパース
    struct TestCase {
        std::vector<std::pair<std::string, std::string>> inputs;    // {name, value}
        std::vector<std::pair<std::string, std::string>> expected;  // {name, value}
        int cycles = 0;  // async用: クロックサイクル数
    };
    std::vector<TestCase> test_cases;

    if (!options_.sourceFile.empty()) {
        std::ifstream src(options_.sourceFile);
        if (src.is_open()) {
            std::string line;
            while (std::getline(src, line)) {
                // "//! test:" プレフィックスを検出
                auto pos = line.find("//! test:");
                if (pos == std::string::npos)
                    continue;
                std::string test_spec = line.substr(pos + 9);

                TestCase tc;
                // "->" で入力と期待出力を分割
                auto arrow = test_spec.find("->");
                std::string input_part, output_part;
                if (arrow != std::string::npos) {
                    input_part = test_spec.substr(0, arrow);
                    output_part = test_spec.substr(arrow + 2);
                } else {
                    input_part = test_spec;
                }

                // 入力パース: "a=3, b=5" or "cycles=5"
                std::istringstream iss(input_part);
                std::string token;
                while (std::getline(iss, token, ',')) {
                    // 空白除去
                    size_t s = token.find_first_not_of(' ');
                    size_t e = token.find_last_not_of(' ');
                    if (s == std::string::npos)
                        continue;
                    token = token.substr(s, e - s + 1);

                    auto eq = token.find('=');
                    if (eq != std::string::npos) {
                        std::string name = token.substr(0, eq);
                        std::string val = token.substr(eq + 1);
                        // 名前と値の空白除去
                        size_t ns = name.find_first_not_of(' ');
                        size_t ne = name.find_last_not_of(' ');
                        if (ns != std::string::npos)
                            name = name.substr(ns, ne - ns + 1);
                        size_t vs = val.find_first_not_of(' ');
                        size_t ve = val.find_last_not_of(' ');
                        if (vs != std::string::npos)
                            val = val.substr(vs, ve - vs + 1);

                        if (name == "cycles") {
                            tc.cycles = std::stoi(val);
                        } else {
                            tc.inputs.push_back({name, val});
                        }
                    }
                }

                // 期待出力パース: "result=8, out=0"
                if (!output_part.empty()) {
                    std::istringstream oss(output_part);
                    while (std::getline(oss, token, ',')) {
                        size_t s = token.find_first_not_of(' ');
                        size_t e = token.find_last_not_of(' ');
                        if (s == std::string::npos)
                            continue;
                        token = token.substr(s, e - s + 1);

                        auto eq = token.find('=');
                        if (eq != std::string::npos) {
                            std::string name = token.substr(0, eq);
                            std::string val = token.substr(eq + 1);
                            size_t ns = name.find_first_not_of(' ');
                            size_t ne = name.find_last_not_of(' ');
                            if (ns != std::string::npos)
                                name = name.substr(ns, ne - ns + 1);
                            size_t vs = val.find_first_not_of(' ');
                            size_t ve = val.find_last_not_of(' ');
                            if (vs != std::string::npos)
                                val = val.substr(vs, ve - vs + 1);
                            tc.expected.push_back({name, val});
                        }
                    }
                }

                test_cases.push_back(tc);
            }
        }
    }

    ss << "// 自動生成テストベンチ - Cm compiler\n";
    ss << "`timescale 1ns / 1ps\n\n";

    ss << "module " << mod.name << "_tb;\n\n";

    // ポートに対応する信号宣言
    for (const auto& port : mod.ports) {
        ss << "    " << port.sv_type << " " << port.name << ";\n";
    }
    ss << "\n";

    // DUTインスタンス化
    ss << "    // DUTインスタンス\n";
    ss << "    " << mod.name << " dut (\n";
    for (size_t i = 0; i < mod.ports.size(); ++i) {
        ss << "        ." << mod.ports[i].name << "(" << mod.ports[i].name << ")";
        if (i + 1 < mod.ports.size())
            ss << ",";
        ss << "\n";
    }
    ss << "    );\n\n";

    // クロック生成（clkポートがある場合）
    bool has_clk = false;
    std::string rst_name;         // リセット信号の実際のポート名
    bool rst_active_low = false;  // アクティブLowリセットかどうか
    for (const auto& port : mod.ports) {
        if (port.name == "clk" && port.direction == SVPort::Input)
            has_clk = true;
        if (port.direction == SVPort::Input) {
            if (port.name == "rst") {
                rst_name = "rst";
                rst_active_low = false;
            } else if (port.name == "rst_n") {
                rst_name = "rst_n";
                rst_active_low = true;
            }
        }
    }
    bool has_rst = !rst_name.empty();

    if (has_clk) {
        ss << "    // クロック生成 (10ns周期 = 100MHz)\n";
        ss << "    initial clk = 0;\n";
        ss << "    always #5 clk = ~clk;\n\n";
    }

    // テストシーケンス
    ss << "    // テストシーケンス\n";
    ss << "    initial begin\n";
    ss << "        $dumpfile(\"" << mod.name << "_tb.vcd\");\n";
    ss << "        $dumpvars(0, " << mod.name << "_tb);\n\n";

    // 入力ポート初期化
    for (const auto& port : mod.ports) {
        if (port.direction == SVPort::Input && port.name != "clk") {
            ss << "        " << port.name << " = 0;\n";
        }
    }
    ss << "\n";

    // リセットシーケンス（実際のポート名を使用）
    if (has_rst) {
        ss << "        // リセット\n";
        if (rst_active_low) {
            // アクティブLow: 0→1（リセット解除）
            ss << "        " << rst_name << " = 0;\n";
            ss << "        #20;\n";
            ss << "        " << rst_name << " = 1;\n";
        } else {
            // アクティブHigh: 1→0（リセット解除）
            ss << "        " << rst_name << " = 1;\n";
            ss << "        #20;\n";
            ss << "        " << rst_name << " = 0;\n";
        }
        ss << "        #10;\n\n";
    }

    if (!test_cases.empty()) {
        // テストシナリオベースの検証
        int test_num = 1;
        for (const auto& tc : test_cases) {
            ss << "        // テスト " << test_num << "\n";

            // 入力値設定
            for (const auto& [name, val] : tc.inputs) {
                ss << "        " << name << " = " << val << ";\n";
            }

            // 評価待ち
            if (tc.cycles > 0) {
                // async: 指定サイクル分クロックを待つ
                ss << "        repeat(" << tc.cycles << ") @(posedge clk);\n";
                ss << "        #1; // 安定化\n";
            } else if (has_clk) {
                // クロック付きだがcycles未指定: 1サイクル待ち
                ss << "        @(posedge clk);\n";
                ss << "        #1;\n";
            } else {
                // 組み合わせ回路: 伝搬遅延待ち
                ss << "        #10;\n";
            }

            // 出力値の表示と検証
            for (const auto& [name, val] : tc.expected) {
                ss << "        $display(\"TEST " << test_num << ": " << name << "=%0d\", " << name
                   << ");\n";
            }
            ss << "\n";
            test_num++;
        }
    } else {
        // テストシナリオなし: 基本的な動作確認
        ss << "        // テスト実行\n";
        ss << "        #100;\n\n";
    }

    ss << "        $display(\"=== Test Complete ===\");\n";
    ss << "        $finish;\n";
    ss << "    end\n\n";

    ss << "endmodule\n";

    return ss.str();
}

// === XDC制約ファイル生成 ===

std::string SVCodeGen::generateXDC(const mir::MirProgram& program) {
    std::ostringstream ss;
    bool has_pins = false;

    for (const auto& gv : program.global_vars) {
        if (!gv)
            continue;

        std::string pin_name;
        std::string iostandard = "LVCMOS33";  // デフォルト

        for (const auto& attr : gv->attributes) {
            // sv::pin("XX") 形式の解析
            std::string prefix1 = "sv::pin(\"";
            std::string prefix2 = "verilog::pin(\"";
            if (attr.find(prefix1) == 0 && attr.size() > prefix1.size() + 2) {
                pin_name = attr.substr(prefix1.size(), attr.size() - prefix1.size() - 2);
            } else if (attr.find(prefix2) == 0 && attr.size() > prefix2.size() + 2) {
                pin_name = attr.substr(prefix2.size(), attr.size() - prefix2.size() - 2);
            }

            // sv::iostandard("XX") 形式の解析
            std::string io_prefix1 = "sv::iostandard(\"";
            std::string io_prefix2 = "verilog::iostandard(\"";
            if (attr.find(io_prefix1) == 0 && attr.size() > io_prefix1.size() + 2) {
                iostandard = attr.substr(io_prefix1.size(), attr.size() - io_prefix1.size() - 2);
            } else if (attr.find(io_prefix2) == 0 && attr.size() > io_prefix2.size() + 2) {
                iostandard = attr.substr(io_prefix2.size(), attr.size() - io_prefix2.size() - 2);
            }
        }

        if (!pin_name.empty()) {
            if (!has_pins) {
                ss << "## Cm compiler 自動生成 XDC 制約ファイル\n\n";
                has_pins = true;
            }
            ss << "set_property -dict { PACKAGE_PIN " << pin_name << "  IOSTANDARD " << iostandard
               << " } [get_ports {" << gv->name << "}]\n";

            // clk ポートにはクロック制約を追加
            if (gv->name.find("clk") != std::string::npos) {
                ss << "create_clock -add -name " << gv->name << "_pin -period 10.00 [get_ports {"
                   << gv->name << "}]\n";
            }
        }
    }

    return ss.str();
}

// === 非合成型チェック ===

void SVCodeGen::validateSynthesizableTypes(const mir::MirProgram& program) {
    for (const auto& gv : program.global_vars) {
        if (!gv || !gv->type)
            continue;

        switch (gv->type->kind) {
            case hir::TypeKind::Pointer:
                std::cerr << "error[SV002]: Pointer types are not supported in SV target: "
                          << gv->name << "\n";
                break;
            case hir::TypeKind::String:
                std::cerr << "error[SV003]: String types are not synthesizable: " << gv->name
                          << "\n";
                break;
            case hir::TypeKind::Float:
            case hir::TypeKind::Double:
                std::cerr << "warning[SV004]: Floating-point requires IP core: " << gv->name
                          << "\n";
                break;
            default:
                break;
        }
    }

    for (const auto& func : program.functions) {
        if (!func)
            continue;
        for (const auto& local : func->locals) {
            if (!local.type)
                continue;
            switch (local.type->kind) {
                case hir::TypeKind::Pointer:
                    std::cerr << "error[SV002]: Pointer types not supported in SV target: "
                              << func->name << "::" << local.name << "\n";
                    break;
                case hir::TypeKind::String:
                    std::cerr << "error[SV003]: String types not synthesizable: " << func->name
                              << "::" << local.name << "\n";
                    break;
                default:
                    break;
            }
        }
    }
}

}  // namespace cm::codegen::sv
