#include "token.hpp"

namespace cm {

const char* token_kind_to_string(TokenKind kind) {
    switch (kind) {
        case TokenKind::IntLiteral:
            return "int literal";
        case TokenKind::FloatLiteral:
            return "float literal";
        case TokenKind::StringLiteral:
            return "string literal";
        case TokenKind::CharLiteral:
            return "char literal";
        case TokenKind::Ident:
            return "identifier";

        // キーワード
        case TokenKind::KwAs:
            return "as";
        case TokenKind::KwAsync:
            return "async";
        case TokenKind::KwAwait:
            return "await";
        case TokenKind::KwBreak:
            return "break";
        case TokenKind::KwCase:
            return "case";
        case TokenKind::KwConst:
            return "const";
        case TokenKind::KwConstexpr:
            return "constexpr";
        case TokenKind::KwContinue:
            return "continue";
        case TokenKind::KwDefault:
            return "default";
        case TokenKind::KwDefer:
            return "defer";
        case TokenKind::KwDelete:
            return "delete";
        case TokenKind::KwElse:
            return "else";
        case TokenKind::KwEnum:
            return "enum";
        case TokenKind::KwExport:
            return "export";
        case TokenKind::KwExtern:
            return "extern";
        case TokenKind::KwFalse:
            return "false";
        case TokenKind::KwFor:
            return "for";
        case TokenKind::KwFrom:
            return "from";
        case TokenKind::KwIf:
            return "if";
        case TokenKind::KwImpl:
            return "impl";
        case TokenKind::KwImport:
            return "import";
        case TokenKind::KwIn:
            return "in";
        case TokenKind::KwInline:
            return "inline";
        case TokenKind::KwInterface:
            return "interface";
        case TokenKind::KwMacro:
            return "macro";
        case TokenKind::KwMatch:
            return "match";
        case TokenKind::KwModule:
            return "module";
        case TokenKind::KwMutable:
            return "mutable";
        case TokenKind::KwNamespace:
            return "namespace";
        case TokenKind::KwNew:
            return "new";
        case TokenKind::KwNull:
            return "null";
        case TokenKind::KwOperator:
            return "operator";
        case TokenKind::KwOverload:
            return "overload";
        case TokenKind::KwPrivate:
            return "private";
        case TokenKind::KwPub:
            return "pub";
        case TokenKind::KwReturn:
            return "return";
        case TokenKind::KwStatic:
            return "static";
        case TokenKind::KwStruct:
            return "struct";
        case TokenKind::KwSwitch:
            return "switch";
        case TokenKind::KwTemplate:
            return "template";
        case TokenKind::KwThis:
            return "this";
        case TokenKind::KwTrue:
            return "true";
        case TokenKind::KwTypedef:
            return "typedef";
        case TokenKind::KwTypename:
            return "typename";
        case TokenKind::KwUse:
            return "use";
        case TokenKind::KwVoid:
            return "void";
        case TokenKind::KwVolatile:
            return "volatile";
        case TokenKind::KwWhere:
            return "where";
        case TokenKind::KwWhile:
            return "while";
        case TokenKind::KwWith:
            return "with";

        // 型・演算子キーワード
        case TokenKind::KwAuto:
            return "auto";
        case TokenKind::KwSizeof:
            return "sizeof";
        case TokenKind::KwTypeof:
            return "typeof";

        // Intrinsicキーワード
        case TokenKind::KwIntrinsicSizeof:
            return "__sizeof__";
        case TokenKind::KwIntrinsicTypeof:
            return "__typeof__";
        case TokenKind::KwIntrinsicTypename:
            return "__typename__";
        case TokenKind::KwIntrinsicAlignof:
            return "__alignof__";

        // 型キーワード
        case TokenKind::KwInt:
            return "int";
        case TokenKind::KwUint:
            return "uint";
        case TokenKind::KwTiny:
            return "tiny";
        case TokenKind::KwUtiny:
            return "utiny";
        case TokenKind::KwShort:
            return "short";
        case TokenKind::KwUshort:
            return "ushort";
        case TokenKind::KwLong:
            return "long";
        case TokenKind::KwUlong:
            return "ulong";
        case TokenKind::KwFloat:
            return "float";
        case TokenKind::KwDouble:
            return "double";
        case TokenKind::KwUfloat:
            return "ufloat";
        case TokenKind::KwUdouble:
            return "udouble";
        case TokenKind::KwBool:
            return "bool";
        case TokenKind::KwChar:
            return "char";
        case TokenKind::KwString:
            return "string";
        case TokenKind::KwIsize:
            return "isize";
        case TokenKind::KwUsize:
            return "usize";
        case TokenKind::KwCstring:
            return "cstring";

        // 演算子
        case TokenKind::Plus:
            return "+";
        case TokenKind::Minus:
            return "-";
        case TokenKind::Star:
            return "*";
        case TokenKind::Slash:
            return "/";
        case TokenKind::Percent:
            return "%";
        case TokenKind::Amp:
            return "&";
        case TokenKind::Pipe:
            return "|";
        case TokenKind::Caret:
            return "^";
        case TokenKind::Tilde:
            return "~";
        case TokenKind::LtLt:
            return "<<";
        case TokenKind::GtGt:
            return ">>";
        case TokenKind::AmpAmp:
            return "&&";
        case TokenKind::PipePipe:
            return "||";
        case TokenKind::Bang:
            return "!";
        case TokenKind::Eq:
            return "=";
        case TokenKind::EqEq:
            return "==";
        case TokenKind::BangEq:
            return "!=";
        case TokenKind::Lt:
            return "<";
        case TokenKind::Gt:
            return ">";
        case TokenKind::LtEq:
            return "<=";
        case TokenKind::GtEq:
            return ">=";
        case TokenKind::PlusEq:
            return "+=";
        case TokenKind::MinusEq:
            return "-=";
        case TokenKind::StarEq:
            return "*=";
        case TokenKind::SlashEq:
            return "/=";
        case TokenKind::PercentEq:
            return "%=";
        case TokenKind::AmpEq:
            return "&=";
        case TokenKind::PipeEq:
            return "|=";
        case TokenKind::CaretEq:
            return "^=";
        case TokenKind::LtLtEq:
            return "<<=";
        case TokenKind::GtGtEq:
            return ">>=";
        case TokenKind::PlusPlus:
            return "++";
        case TokenKind::MinusMinus:
            return "--";
        case TokenKind::Question:
            return "?";
        case TokenKind::Colon:
            return ":";
        case TokenKind::ColonColon:
            return "::";
        case TokenKind::Arrow:
            return "=>";
        case TokenKind::ThinArrow:
            return "->";
        case TokenKind::At:
            return "@";
        case TokenKind::Ellipsis:
            return "...";
        case TokenKind::Hash:
            return "#";

        // 区切り
        case TokenKind::LParen:
            return "(";
        case TokenKind::RParen:
            return ")";
        case TokenKind::LBrace:
            return "{";
        case TokenKind::RBrace:
            return "}";
        case TokenKind::LBracket:
            return "[";
        case TokenKind::RBracket:
            return "]";
        case TokenKind::Comma:
            return ",";
        case TokenKind::Semicolon:
            return ";";
        case TokenKind::Dot:
            return ".";

        case TokenKind::Eof:
            return "end of file";
        case TokenKind::Error:
            return "error";
    }
    return "unknown";
}

}  // namespace cm
