source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

# Ruby 3.x互換性
gem "base64"
gem "bigdecimal"
gem "csv"
gem "logger"
gem "webrick"

group :jekyll_plugins do
  gem "jekyll-relative-links"
  gem "jekyll-optional-front-matter"
  gem "jekyll-readme-index"
  gem "jekyll-titles-from-headings"
end
