#pragma once

// ============================================================
// ランタイムビルトインレジストリ（runtime-builtin-registry 第1段）
// ランタイム関数の名前とシグネチャを単一の表として定義し、LLVMの宣言（declareBuiltinRuntimeFunction）は本表からの導出とする。
// 従来はelse-if連鎖117分岐に文字列名とシグネチャが分散し、関数追加のたびに宣言・写像・実装の多重同期が必要だった。
// ランタイム関数を追加・変更する場合は必ず本表を更新すること（宣言側への手書き分岐の追加は禁止）
// ============================================================

#include <cstddef>
#include <string>

namespace cm::codegen {

// シグネチャの型タグ（LLVM型へは各バックエンドが写像する）
enum class TypeTag {
    Void,
    I1,
    I8,
    I16,
    I32,
    I64,
    F32,
    F64,
    Ptr,
};

// ビルトイン1件のシグネチャ
struct BuiltinSig {
    const char* name;  // Cm側の参照名
    const char* symbol;  // 実シンボル名（nullptrならnameと同一。例: __println__→printf）
    TypeTag ret;
    TypeTag args[6];
    size_t num_args;
    bool vararg;
};

// 名前昇順の表（188件）。declareBuiltinRuntimeFunction由来の全シグネチャを収容する
inline constexpr BuiltinSig kBuiltinSigs[] = {
    {"__builtin_array_every",
     nullptr,
     TypeTag::I8,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_every_i32",
     nullptr,
     TypeTag::I8,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_every_i32_closure",
     nullptr,
     TypeTag::I8,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_every_i64_closure",
     nullptr,
     TypeTag::I8,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_filter",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_filter_closure",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_filter_i32",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_filter_i32_closure",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_filter_i64",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_filter_i64_closure",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_find",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_findIndex",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_findIndex_i32",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_findIndex_i32_closure",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_findIndex_i64_closure",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_find_i32",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_find_i64",
     nullptr,
     TypeTag::I64,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_first", nullptr, TypeTag::I32, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_array_first_i32", nullptr, TypeTag::I32, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_array_first_i64", nullptr, TypeTag::I64, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_array_forEach",
     nullptr,
     TypeTag::Void,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_forEach_i32",
     nullptr,
     TypeTag::Void,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_forEach_i32_closure",
     nullptr,
     TypeTag::Void,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_forEach_i64_closure",
     nullptr,
     TypeTag::Void,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_includes",
     nullptr,
     TypeTag::I8,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::I32},
     3,
     false},
    {"__builtin_array_includes_i32",
     nullptr,
     TypeTag::I8,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::I32},
     3,
     false},
    {"__builtin_array_includes_i64",
     nullptr,
     TypeTag::I8,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::I64},
     3,
     false},
    {"__builtin_array_indexOf",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::I32},
     3,
     false},
    {"__builtin_array_indexOf_i32",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::I32},
     3,
     false},
    {"__builtin_array_indexOf_i64",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::I64},
     3,
     false},
    {"__builtin_array_last", nullptr, TypeTag::I32, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_array_last_i32", nullptr, TypeTag::I32, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_array_last_i64", nullptr, TypeTag::I64, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_array_map",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_map_closure",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_map_i32",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_map_i32_closure",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_map_i64",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_map_i64_closure",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_reduce",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::I32},
     4,
     false},
    {"__builtin_array_reduce_i32",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::I32},
     4,
     false},
    {"__builtin_array_reduce_i32_acc64",
     nullptr,
     TypeTag::I64,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::I64},
     4,
     false},
    {"__builtin_array_reduce_i32_acc64_closure",
     nullptr,
     TypeTag::I64,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     5,
     false},
    {"__builtin_array_reduce_i32_closure",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::I32, TypeTag::Ptr},
     5,
     false},
    {"__builtin_array_reduce_i64",
     nullptr,
     TypeTag::I64,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::I64},
     4,
     false},
    {"__builtin_array_reduce_i64_closure",
     nullptr,
     TypeTag::I64,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     5,
     false},
    {"__builtin_array_reverse", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_array_reverse_i32", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_array_reverse_i64", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_array_slice",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::I64, TypeTag::I64, TypeTag::I64, TypeTag::Ptr},
     6,
     false},
    {"__builtin_array_some",
     nullptr,
     TypeTag::I8,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_some_i32",
     nullptr,
     TypeTag::I8,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_some_i32_closure",
     nullptr,
     TypeTag::I8,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_some_i64_closure",
     nullptr,
     TypeTag::I8,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"__builtin_array_sort", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_array_sortBy",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_sortBy_i32",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_sortBy_i64",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::Ptr},
     3,
     false},
    {"__builtin_array_sort_i32", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_array_sort_i64", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_slice_get_f32", nullptr, TypeTag::F32, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_slice_get_f64", nullptr, TypeTag::F64, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_slice_get_i16", nullptr, TypeTag::I16, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_slice_get_i32", nullptr, TypeTag::I32, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_slice_get_i64", nullptr, TypeTag::I64, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_slice_get_i8", nullptr, TypeTag::I8, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_slice_get_ptr", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_string_charAt", nullptr, TypeTag::I8, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_string_chars", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"__builtin_string_codepoint_at",
     nullptr,
     TypeTag::I32,
     {TypeTag::Ptr, TypeTag::I64},
     2,
     false},
    {"__builtin_string_codepoint_len", nullptr, TypeTag::I64, {TypeTag::Ptr}, 1, false},
    {"__builtin_string_endsWith", nullptr, TypeTag::I1, {TypeTag::Ptr, TypeTag::Ptr}, 2, false},
    {"__builtin_string_first", nullptr, TypeTag::I8, {TypeTag::Ptr}, 1, false},
    {"__builtin_string_includes", nullptr, TypeTag::I1, {TypeTag::Ptr, TypeTag::Ptr}, 2, false},
    {"__builtin_string_indexOf", nullptr, TypeTag::I64, {TypeTag::Ptr, TypeTag::Ptr}, 2, false},
    {"__builtin_string_last", nullptr, TypeTag::I8, {TypeTag::Ptr}, 1, false},
    {"__builtin_string_len", nullptr, TypeTag::I64, {TypeTag::Ptr}, 1, false},
    {"__builtin_string_repeat", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"__builtin_string_replace",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::Ptr, TypeTag::Ptr},
     3,
     false},
    {"__builtin_string_startsWith", nullptr, TypeTag::I1, {TypeTag::Ptr, TypeTag::Ptr}, 2, false},
    {"__builtin_string_substring",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::I64},
     3,
     false},
    {"__builtin_string_toLowerCase", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"__builtin_string_toUpperCase", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"__builtin_string_trim", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"__print__", "printf", TypeTag::I32, {TypeTag::Ptr}, 1, true},
    {"__println__", "printf", TypeTag::I32, {TypeTag::Ptr}, 1, true},
    {"cm_args_init", nullptr, TypeTag::Void, {TypeTag::I32, TypeTag::Ptr}, 2, false},
    {"cm_array_equal",
     nullptr,
     TypeTag::I1,
     {TypeTag::Ptr, TypeTag::Ptr, TypeTag::I64, TypeTag::I64, TypeTag::I64},
     5,
     false},
    {"cm_array_to_slice",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::I64},
     3,
     false},
    {"cm_bool_to_string", nullptr, TypeTag::Ptr, {TypeTag::I8}, 1, false},
    {"cm_bounds_error", nullptr, TypeTag::Void, {TypeTag::I64, TypeTag::I64}, 2, false},
    {"cm_char_to_string", nullptr, TypeTag::Ptr, {TypeTag::I8}, 1, false},
    {"cm_double_to_string", nullptr, TypeTag::Ptr, {TypeTag::F64}, 1, false},
    {"cm_format_bool", nullptr, TypeTag::Ptr, {TypeTag::I8}, 1, false},
    {"cm_format_char", nullptr, TypeTag::Ptr, {TypeTag::I8}, 1, false},
    {"cm_format_double", nullptr, TypeTag::Ptr, {TypeTag::F64}, 1, false},
    {"cm_format_int", nullptr, TypeTag::Ptr, {TypeTag::I32}, 1, false},
    {"cm_format_string", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I32}, 2, true},
    {"cm_format_uint", nullptr, TypeTag::Ptr, {TypeTag::I32}, 1, false},
    {"cm_int_to_string", nullptr, TypeTag::Ptr, {TypeTag::I32}, 1, false},
    {"cm_long_to_string", nullptr, TypeTag::Ptr, {TypeTag::I64}, 1, false},
    {"cm_print_bool", nullptr, TypeTag::Void, {TypeTag::I8}, 1, false},
    {"cm_print_char", nullptr, TypeTag::Void, {TypeTag::I8}, 1, false},
    {"cm_print_double", nullptr, TypeTag::Void, {TypeTag::F64}, 1, false},
    {"cm_print_float", nullptr, TypeTag::Void, {TypeTag::F32}, 1, false},
    {"cm_print_format", nullptr, TypeTag::Void, {TypeTag::Ptr, TypeTag::I32}, 2, true},
    {"cm_print_int", nullptr, TypeTag::Void, {TypeTag::I32}, 1, false},
    {"cm_print_long", nullptr, TypeTag::Void, {TypeTag::I64}, 1, false},
    {"cm_print_string", nullptr, TypeTag::Void, {TypeTag::Ptr}, 1, false},
    {"cm_print_uint", nullptr, TypeTag::Void, {TypeTag::I32}, 1, false},
    {"cm_print_ulong", nullptr, TypeTag::Void, {TypeTag::I64}, 1, false},
    {"cm_println_bool", nullptr, TypeTag::Void, {TypeTag::I8}, 1, false},
    {"cm_println_char", nullptr, TypeTag::Void, {TypeTag::I8}, 1, false},
    {"cm_println_double", nullptr, TypeTag::Void, {TypeTag::F64}, 1, false},
    {"cm_println_float", nullptr, TypeTag::Void, {TypeTag::F32}, 1, false},
    {"cm_println_format", nullptr, TypeTag::Void, {TypeTag::Ptr, TypeTag::I32}, 2, true},
    {"cm_println_int", nullptr, TypeTag::Void, {TypeTag::I32}, 1, false},
    {"cm_println_long", nullptr, TypeTag::Void, {TypeTag::I64}, 1, false},
    {"cm_println_string", nullptr, TypeTag::Void, {TypeTag::Ptr}, 1, false},
    {"cm_println_uint", nullptr, TypeTag::Void, {TypeTag::I32}, 1, false},
    {"cm_println_ulong", nullptr, TypeTag::Void, {TypeTag::I64}, 1, false},
    {"cm_slice_cap", nullptr, TypeTag::I64, {TypeTag::Ptr}, 1, false},
    {"cm_slice_clear", nullptr, TypeTag::Void, {TypeTag::Ptr}, 1, false},
    {"cm_slice_delete", nullptr, TypeTag::Void, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"cm_slice_elem_size", nullptr, TypeTag::I64, {TypeTag::Ptr}, 1, false},
    {"cm_slice_equal", nullptr, TypeTag::I1, {TypeTag::Ptr, TypeTag::Ptr}, 2, false},
    {"cm_slice_first_i32", nullptr, TypeTag::I32, {TypeTag::Ptr}, 1, false},
    {"cm_slice_first_i64", nullptr, TypeTag::I64, {TypeTag::Ptr}, 1, false},
    {"cm_slice_first_ptr", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_free", nullptr, TypeTag::Void, {TypeTag::Ptr}, 1, false},
    {"cm_slice_get_element_ptr", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"cm_slice_get_f32", nullptr, TypeTag::F32, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"cm_slice_get_f64", nullptr, TypeTag::F64, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"cm_slice_get_i16", nullptr, TypeTag::I16, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"cm_slice_get_i32", nullptr, TypeTag::I32, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"cm_slice_get_i64", nullptr, TypeTag::I64, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"cm_slice_get_i8", nullptr, TypeTag::I8, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"cm_slice_get_ptr", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"cm_slice_get_subslice", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"cm_slice_get_subslice_ref", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"cm_slice_last_i32", nullptr, TypeTag::I32, {TypeTag::Ptr}, 1, false},
    {"cm_slice_last_i64", nullptr, TypeTag::I64, {TypeTag::Ptr}, 1, false},
    {"cm_slice_last_ptr", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_len", nullptr, TypeTag::I64, {TypeTag::Ptr}, 1, false},
    {"cm_slice_new", nullptr, TypeTag::Ptr, {TypeTag::I64, TypeTag::I64}, 2, false},
    {"cm_slice_pop_blob", nullptr, TypeTag::Void, {TypeTag::Ptr}, 1, false},
    {"cm_slice_pop_f32", nullptr, TypeTag::F32, {TypeTag::Ptr}, 1, false},
    {"cm_slice_pop_f64", nullptr, TypeTag::F64, {TypeTag::Ptr}, 1, false},
    {"cm_slice_pop_i16", nullptr, TypeTag::I16, {TypeTag::Ptr}, 1, false},
    {"cm_slice_pop_i32", nullptr, TypeTag::I32, {TypeTag::Ptr}, 1, false},
    {"cm_slice_pop_i64", nullptr, TypeTag::I64, {TypeTag::Ptr}, 1, false},
    {"cm_slice_pop_i8", nullptr, TypeTag::I8, {TypeTag::Ptr}, 1, false},
    {"cm_slice_pop_ptr", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_push_blob", nullptr, TypeTag::Void, {TypeTag::Ptr, TypeTag::Ptr}, 2, false},
    {"cm_slice_push_f32", nullptr, TypeTag::Void, {TypeTag::Ptr, TypeTag::F32}, 2, false},
    {"cm_slice_push_f64", nullptr, TypeTag::Void, {TypeTag::Ptr, TypeTag::F64}, 2, false},
    {"cm_slice_push_i16", nullptr, TypeTag::Void, {TypeTag::Ptr, TypeTag::I16}, 2, false},
    {"cm_slice_push_i32", nullptr, TypeTag::Void, {TypeTag::Ptr, TypeTag::I32}, 2, false},
    {"cm_slice_push_i64", nullptr, TypeTag::Void, {TypeTag::Ptr, TypeTag::I64}, 2, false},
    {"cm_slice_push_i8", nullptr, TypeTag::Void, {TypeTag::Ptr, TypeTag::I8}, 2, false},
    {"cm_slice_push_ptr", nullptr, TypeTag::Void, {TypeTag::Ptr, TypeTag::Ptr}, 2, false},
    {"cm_slice_push_slice", nullptr, TypeTag::Void, {TypeTag::Ptr, TypeTag::Ptr}, 2, false},
    {"cm_slice_reverse", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_sort", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_sort_f32", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_sort_f64", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_sort_i16", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_sort_i32", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_sort_i64", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_sort_i8", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_sort_str", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_sort_u16", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_sort_u32", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_sort_u64", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_sort_u8", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_slice_subslice",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::I64, TypeTag::I64},
     3,
     false},
    {"cm_strcmp", nullptr, TypeTag::I32, {TypeTag::Ptr, TypeTag::Ptr}, 2, false},
    {"cm_string_concat", nullptr, TypeTag::Ptr, {TypeTag::Ptr, TypeTag::Ptr}, 2, false},
    {"cm_string_concat3",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::Ptr, TypeTag::Ptr},
     3,
     false},
    {"cm_string_concat4",
     nullptr,
     TypeTag::Ptr,
     {TypeTag::Ptr, TypeTag::Ptr, TypeTag::Ptr, TypeTag::Ptr},
     4,
     false},
    {"cm_string_free", nullptr, TypeTag::Void, {TypeTag::Ptr}, 1, false},
    {"cm_string_from_byte_slice", nullptr, TypeTag::Ptr, {TypeTag::Ptr}, 1, false},
    {"cm_strlen", nullptr, TypeTag::I64, {TypeTag::Ptr}, 1, false},
    {"cm_strncmp", nullptr, TypeTag::I32, {TypeTag::Ptr, TypeTag::Ptr, TypeTag::I64}, 3, false},
    {"cm_uint_to_string", nullptr, TypeTag::Ptr, {TypeTag::I32}, 1, false},
    {"cm_ulong_to_string", nullptr, TypeTag::Ptr, {TypeTag::I64}, 1, false},
    {"printf", "printf", TypeTag::I32, {TypeTag::Ptr}, 1, true},
    {"puts", "puts", TypeTag::I32, {TypeTag::Ptr}, 1, false},
};

// 名前でシグネチャを検索する（見つからなければnullptr）
inline const BuiltinSig* find_builtin_sig(const std::string& name) {
    // 表は名前昇順のため二分探索する
    size_t lo = 0;
    size_t hi = sizeof(kBuiltinSigs) / sizeof(kBuiltinSigs[0]);
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        int cmp = name.compare(kBuiltinSigs[mid].name);
        if (cmp == 0) {
            return &kBuiltinSigs[mid];
        }
        if (cmp < 0) {
            hi = mid;
        } else {
            lo = mid + 1;
        }
    }
    return nullptr;
}

}  // namespace cm::codegen
